create table public.order_artisan_group_status_history (
  id bigint generated by default as identity primary key,
  artisan_group_id uuid not null references public.order_artisan_groups(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  artisan_id uuid not null references public.artisan_profiles(id),
  from_status text not null,
  to_status text not null,
  changed_by_user_id uuid references auth.users(id) on delete set null,
  source text not null default 'artisan',
  created_at timestamptz not null default now(),
  constraint order_artisan_group_status_history_transition check (
    (from_status in ('received', 'confirmed') and to_status = 'preparing')
    or (from_status = 'preparing' and to_status = 'ready_for_courier_pickup')
  )
);

create index order_artisan_group_status_history_group_created_idx
  on public.order_artisan_group_status_history(artisan_group_id, created_at desc);

create index order_artisan_group_status_history_order_created_idx
  on public.order_artisan_group_status_history(order_id, created_at desc);

alter table public.order_artisan_group_status_history enable row level security;

revoke all on public.order_artisan_group_status_history from anon, authenticated;

create or replace function private.update_my_artisan_fulfillment_status(
  p_artisan_group_id uuid,
  p_target_status text
)
returns table(
  artisan_group_id uuid,
  order_id uuid,
  previous_status text,
  fulfillment_status text,
  changed boolean,
  changed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_order_id uuid;
  v_artisan_id uuid;
  v_current_status text;
  v_target_status text := lower(trim(coalesce(p_target_status, '')));
  v_changed_at timestamptz := now();
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if p_artisan_group_id is null then
    raise exception 'artisan_group_required';
  end if;

  if v_target_status not in ('preparing', 'ready_for_courier_pickup') then
    raise exception 'invalid_fulfillment_target';
  end if;

  select g.order_id, g.artisan_id, g.fulfillment_status
  into v_order_id, v_artisan_id, v_current_status
  from public.order_artisan_groups g
  join public.artisan_profiles a
    on a.id = g.artisan_id
   and a.auth_user_id = v_user_id
  where g.id = p_artisan_group_id
  for update of g;

  if not found then
    raise exception 'artisan_group_not_found';
  end if;

  if v_current_status = v_target_status then
    return query
    select p_artisan_group_id, v_order_id, v_current_status, v_current_status, false, null::timestamptz;
    return;
  end if;

  if v_target_status = 'preparing' and v_current_status not in ('received', 'confirmed') then
    raise exception 'invalid_fulfillment_transition';
  end if;

  if v_target_status = 'ready_for_courier_pickup' and v_current_status <> 'preparing' then
    raise exception 'invalid_fulfillment_transition';
  end if;

  update public.order_artisan_groups
  set fulfillment_status = v_target_status,
      updated_at = v_changed_at
  where id = p_artisan_group_id;

  insert into public.order_artisan_group_status_history (
    artisan_group_id,
    order_id,
    artisan_id,
    from_status,
    to_status,
    changed_by_user_id,
    source,
    created_at
  ) values (
    p_artisan_group_id,
    v_order_id,
    v_artisan_id,
    v_current_status,
    v_target_status,
    v_user_id,
    'artisan',
    v_changed_at
  );

  return query
  select p_artisan_group_id, v_order_id, v_current_status, v_target_status, true, v_changed_at;
end;
$$;

revoke all on function private.update_my_artisan_fulfillment_status(uuid, text) from public, anon, authenticated;
grant execute on function private.update_my_artisan_fulfillment_status(uuid, text) to authenticated;

create or replace function public.update_my_artisan_fulfillment_status(
  p_artisan_group_id uuid,
  p_target_status text
)
returns table(
  artisan_group_id uuid,
  order_id uuid,
  previous_status text,
  fulfillment_status text,
  changed boolean,
  changed_at timestamptz
)
language sql
security invoker
set search_path = ''
as $$
  select *
  from private.update_my_artisan_fulfillment_status(p_artisan_group_id, p_target_status);
$$;

revoke all on function public.update_my_artisan_fulfillment_status(uuid, text) from public, anon, authenticated;
grant execute on function public.update_my_artisan_fulfillment_status(uuid, text) to authenticated;
