-- IRTH MVP — Dynamic tax foundation (tax-inclusive customer pricing)
-- Approved 2 September 2026.
-- Customer-facing product prices remain unchanged and tax-inclusive.
-- Shipping remains separate. Tax is deducted internally from Artisan settlement.

alter table public.markets
  add column if not exists tax_rate_percent numeric(5,2) not null default 0;

alter table public.markets
  drop constraint if exists markets_tax_rate_percent_range;
alter table public.markets
  add constraint markets_tax_rate_percent_range
  check (tax_rate_percent >= 0 and tax_rate_percent <= 100);

-- Egypt MVP configuration. This is configuration data, not a hardcoded calculation rule.
update public.markets
set tax_rate_percent = 14
where slug = 'egypt'
  and tax_rate_percent = 0;

create table if not exists private.tax_configuration_history (
  id bigint generated by default as identity primary key,
  market_id uuid not null references public.markets(id) on delete restrict,
  previous_rate_percent numeric(5,2) not null,
  new_rate_percent numeric(5,2) not null,
  reason text,
  changed_by_user_id uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now(),
  constraint tax_configuration_history_previous_rate_range check (previous_rate_percent between 0 and 100),
  constraint tax_configuration_history_new_rate_range check (new_rate_percent between 0 and 100),
  constraint tax_configuration_history_reason_length check (reason is null or char_length(reason) between 1 and 1000)
);

create index if not exists tax_configuration_history_market_changed_idx
  on private.tax_configuration_history(market_id, changed_at desc);
create index if not exists tax_configuration_history_changed_by_idx
  on private.tax_configuration_history(changed_by_user_id)
  where changed_by_user_id is not null;

revoke all on table private.tax_configuration_history from public, anon, authenticated, service_role;
grant select on table private.tax_configuration_history to service_role;

alter table public.order_items
  add column if not exists tax_rate_percent numeric(5,2) not null default 0,
  add column if not exists tax_calculation_base_amount numeric not null default 0,
  add column if not exists tax_amount numeric not null default 0;

alter table public.order_items
  drop constraint if exists order_items_tax_rate_percent_range,
  drop constraint if exists order_items_tax_amounts_non_negative;
alter table public.order_items
  add constraint order_items_tax_rate_percent_range
    check (tax_rate_percent >= 0 and tax_rate_percent <= 100),
  add constraint order_items_tax_amounts_non_negative
    check (tax_calculation_base_amount >= 0 and tax_amount >= 0 and tax_amount <= tax_calculation_base_amount);

-- Existing Orders remain historical and are not retroactively taxed.
update public.order_items
set tax_rate_percent = 0,
    tax_calculation_base_amount = 0,
    tax_amount = 0
where created_at < now()
  and tax_rate_percent = 0
  and tax_calculation_base_amount = 0
  and tax_amount = 0;

create or replace function private.snapshot_order_item_tax()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rate numeric(5,2);
  v_scale smallint;
  v_tax_base numeric;
begin
  select m.tax_rate_percent, m.currency_minor_unit_scale
  into v_rate, v_scale
  from public.orders o
  join public.markets m on m.id = o.market_id
  where o.id = new.order_id;

  if not found or v_scale is null or v_rate is null then
    raise exception 'tax_configuration_missing';
  end if;

  -- IRTH-funded discounts preserve Artisan economic entitlement, so the tax
  -- settlement base restores that subsidy before extracting inclusive tax.
  v_tax_base := round(
    new.line_total + new.promotion_funding_irth + new.coupon_funding_irth,
    v_scale
  );

  new.tax_rate_percent := v_rate;
  new.tax_calculation_base_amount := v_tax_base;
  new.tax_amount := case
    when v_rate = 0 then 0
    else round(v_tax_base * v_rate / (100 + v_rate), v_scale)
  end;

  return new;
end;
$$;

revoke all on function private.snapshot_order_item_tax()
  from public, anon, authenticated, service_role;

drop trigger if exists order_item_tax_snapshot on public.order_items;
create trigger order_item_tax_snapshot
before insert on public.order_items
for each row
execute function private.snapshot_order_item_tax();

alter table private.artisan_settlement_ledger
  drop constraint if exists artisan_settlement_ledger_sale_entry_signs;
alter table private.artisan_settlement_ledger
  add constraint artisan_settlement_ledger_sale_entry_signs
  check (
    (entry_type not in ('merchandise_proceeds','irth_discount_subsidy') or amount >= 0)
    and (entry_type <> 'commission' or amount <= 0)
    and (entry_type <> 'tax_withheld' or amount <= 0)
    and (entry_type <> 'refund_tax_reversal' or amount >= 0)
  );

create or replace function private.create_order_item_sale_settlement_entries()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_currency_code text;
  v_currency_scale smallint;
  v_commissionable_amount numeric;
  v_commission_amount numeric;
  v_irth_discount_subsidy numeric;
begin
  select o.currency_code, m.currency_minor_unit_scale
  into v_currency_code, v_currency_scale
  from public.orders o
  join public.markets m on m.id = o.market_id
  where o.id = new.order_id;

  if not found or v_currency_scale is null then
    raise exception 'settlement_currency_configuration_missing';
  end if;

  if new.promotion_discount <> new.promotion_funding_irth + new.promotion_funding_artisan or
     new.coupon_discount <> new.coupon_funding_irth + new.coupon_funding_artisan or
     new.line_total <> new.original_line_total - new.promotion_discount - new.coupon_discount then
    raise exception 'settlement_order_item_snapshot_invalid';
  end if;

  v_irth_discount_subsidy := round(
    new.promotion_funding_irth + new.coupon_funding_irth,
    v_currency_scale
  );

  v_commissionable_amount := round(
    new.line_total + v_irth_discount_subsidy,
    v_currency_scale
  );

  if new.tax_calculation_base_amount <> v_commissionable_amount then
    raise exception 'tax_settlement_base_mismatch';
  end if;

  v_commission_amount := round(
    v_commissionable_amount * new.commission_rate_percent / 100,
    v_currency_scale
  );

  insert into private.artisan_settlement_ledger (
    entry_key, order_id, order_item_id, artisan_group_id, artisan_id,
    currency_code, currency_minor_unit_scale, entry_type, amount,
    calculation_base_amount, rate_percent, source, reference_code, effective_at
  )
  values
    (
      'sale:' || new.id::text || ':merchandise_proceeds',
      new.order_id, new.id, new.artisan_group_id, new.artisan_id,
      v_currency_code, v_currency_scale, 'merchandise_proceeds',
      round(new.line_total, v_currency_scale),
      null, null, 'order_item_sale', new.id::text, new.created_at
    ),
    (
      'sale:' || new.id::text || ':irth_discount_subsidy',
      new.order_id, new.id, new.artisan_group_id, new.artisan_id,
      v_currency_code, v_currency_scale, 'irth_discount_subsidy',
      v_irth_discount_subsidy,
      null, null, 'order_item_sale', new.id::text, new.created_at
    ),
    (
      'sale:' || new.id::text || ':commission',
      new.order_id, new.id, new.artisan_group_id, new.artisan_id,
      v_currency_code, v_currency_scale, 'commission',
      -v_commission_amount,
      v_commissionable_amount, new.commission_rate_percent,
      'order_item_sale', new.id::text, new.created_at
    ),
    (
      'sale:' || new.id::text || ':tax_withheld',
      new.order_id, new.id, new.artisan_group_id, new.artisan_id,
      v_currency_code, v_currency_scale, 'tax_withheld',
      -round(new.tax_amount, v_currency_scale),
      round(new.tax_calculation_base_amount, v_currency_scale), new.tax_rate_percent,
      'order_item_sale', new.id::text, new.created_at
    );

  return new;
end;
$$;

revoke all on function private.create_order_item_sale_settlement_entries()
  from public, anon, authenticated, service_role;

-- Refund snapshots now include the portion of tax originally withheld from the
-- Artisan settlement. No customer-facing refund total is changed by this field.
alter table private.refund_items
  add column if not exists tax_reversal_amount numeric not null default 0;

alter table private.refund_items
  drop constraint if exists refund_items_amounts_non_negative,
  drop constraint if exists refund_items_entitlement_matches,
  drop constraint if exists refund_items_amount_currency_scale;
alter table private.refund_items
  add constraint refund_items_amounts_non_negative check (
    merchandise_refund_amount >= 0
    and irth_subsidy_reversal_amount >= 0
    and commission_reversal_amount >= 0
    and tax_reversal_amount >= 0
    and artisan_entitlement_reversal_amount >= 0
  ),
  add constraint refund_items_entitlement_matches check (
    artisan_entitlement_reversal_amount =
      merchandise_refund_amount + irth_subsidy_reversal_amount - commission_reversal_amount - tax_reversal_amount
  ),
  add constraint refund_items_amount_currency_scale check (
    merchandise_refund_amount = round(merchandise_refund_amount, currency_minor_unit_scale)
    and irth_subsidy_reversal_amount = round(irth_subsidy_reversal_amount, currency_minor_unit_scale)
    and commission_reversal_amount = round(commission_reversal_amount, currency_minor_unit_scale)
    and tax_reversal_amount = round(tax_reversal_amount, currency_minor_unit_scale)
    and artisan_entitlement_reversal_amount = round(artisan_entitlement_reversal_amount, currency_minor_unit_scale)
  );

create or replace function private.snapshot_refund_item_tax_reversal()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order_qty integer;
  v_prior_qty integer;
  v_tax_total numeric;
  v_tax_amount numeric;
begin
  select oi.quantity
  into v_order_qty
  from public.order_items oi
  where oi.id = new.order_item_id;

  if not found or v_order_qty <= 0 then
    raise exception 'refund_order_item_snapshot_missing';
  end if;

  select coalesce(sum(fi.quantity),0)::integer
  into v_prior_qty
  from private.refund_items fi
  join private.refunds fr on fr.id = fi.refund_id
  where fi.order_item_id = new.order_item_id
    and fr.status in ('pending','succeeded');

  select -l.amount
  into v_tax_total
  from private.artisan_settlement_ledger l
  where l.order_item_id = new.order_item_id
    and l.source = 'order_item_sale'
    and l.entry_type = 'tax_withheld'
  limit 1;

  if v_tax_total is null then
    v_tax_total := 0;
  end if;

  v_tax_amount := round(v_tax_total * (v_prior_qty + new.quantity) / v_order_qty, new.currency_minor_unit_scale)
                - round(v_tax_total * v_prior_qty / v_order_qty, new.currency_minor_unit_scale);

  new.tax_reversal_amount := v_tax_amount;
  new.artisan_entitlement_reversal_amount := round(
    new.merchandise_refund_amount
    + new.irth_subsidy_reversal_amount
    - new.commission_reversal_amount
    - v_tax_amount,
    new.currency_minor_unit_scale
  );

  if new.artisan_entitlement_reversal_amount < 0 then
    raise exception 'refund_entitlement_reversal_invalid';
  end if;

  return new;
end;
$$;

revoke all on function private.snapshot_refund_item_tax_reversal()
  from public, anon, authenticated, service_role;

drop trigger if exists refund_item_tax_reversal_snapshot on private.refund_items;
create trigger refund_item_tax_reversal_snapshot
before insert on private.refund_items
for each row
execute function private.snapshot_refund_item_tax_reversal();

create or replace function private.record_refund_tax_ledger_reversal()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item record;
begin
  if old.status <> 'succeeded' and new.status = 'succeeded' then
    for v_item in
      select fi.*, oi.order_id, oi.artisan_group_id, oi.artisan_id, oi.tax_rate_percent
      from private.refund_items fi
      join public.order_items oi on oi.id = fi.order_item_id
      where fi.refund_id = new.id
      order by fi.id
    loop
      if exists (
        select 1 from private.artisan_settlement_ledger l
        where l.order_item_id = v_item.order_item_id
          and l.source = 'order_item_sale'
          and l.entry_type = 'tax_withheld'
      ) then
        insert into private.artisan_settlement_ledger(
          entry_key, order_id, order_item_id, artisan_group_id, artisan_id,
          currency_code, currency_minor_unit_scale, entry_type, amount,
          calculation_base_amount, rate_percent, source, reason, reference_code, effective_at
        ) values (
          'refund:' || new.id::text || ':' || v_item.order_item_id::text || ':tax',
          v_item.order_id, v_item.order_item_id, v_item.artisan_group_id, v_item.artisan_id,
          new.currency_code, new.currency_minor_unit_scale, 'refund_tax_reversal',
          v_item.tax_reversal_amount,
          null, v_item.tax_rate_percent,
          'return_refund', 'approved_return_refund', new.id::text, new.succeeded_at
        )
        on conflict (entry_key) do nothing;
      end if;
    end loop;
  end if;

  return new;
end;
$$;

revoke all on function private.record_refund_tax_ledger_reversal()
  from public, anon, authenticated, service_role;

drop trigger if exists refund_tax_ledger_reversal on private.refunds;
create trigger refund_tax_ledger_reversal
after update of status on private.refunds
for each row
execute function private.record_refund_tax_ledger_reversal();

create or replace function private.set_market_tax_rate(
  p_market_id uuid,
  p_rate_percent numeric,
  p_admin_user_id uuid,
  p_reason text default null
)
returns numeric
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old_rate numeric(5,2);
  v_new_rate numeric(5,2);
  v_reason text := nullif(trim(p_reason),'');
begin
  perform private.require_super_admin_user(p_admin_user_id);

  if p_rate_percent is null or p_rate_percent < 0 or p_rate_percent > 100
     or p_rate_percent <> round(p_rate_percent,2) then
    raise exception 'invalid_tax_rate';
  end if;
  if v_reason is not null and char_length(v_reason) > 1000 then
    raise exception 'invalid_reason';
  end if;

  select m.tax_rate_percent into v_old_rate
  from public.markets m
  where m.id = p_market_id
  for update;
  if not found then raise exception 'market_not_found'; end if;

  v_new_rate := p_rate_percent::numeric(5,2);
  if v_old_rate = v_new_rate then return v_old_rate; end if;

  update public.markets
  set tax_rate_percent = v_new_rate,
      updated_at = now()
  where id = p_market_id;

  insert into private.tax_configuration_history(
    market_id, previous_rate_percent, new_rate_percent, reason, changed_by_user_id
  ) values (
    p_market_id, v_old_rate, v_new_rate, v_reason, p_admin_user_id
  );

  return v_new_rate;
end;
$$;

revoke all on function private.set_market_tax_rate(uuid,numeric,uuid,text)
  from public, anon, authenticated, service_role;

create or replace function public.get_market_tax_settings(p_admin_user_id uuid)
returns table(market_id uuid, slug text, currency_code text, tax_rate_percent numeric)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.require_super_admin_user(p_admin_user_id);
  return query
  select m.id, m.slug, m.currency_code, m.tax_rate_percent::numeric
  from public.markets m
  where m.is_active = true
  order by m.slug;
end;
$$;

revoke all on function public.get_market_tax_settings(uuid)
  from public, anon, authenticated;
grant execute on function public.get_market_tax_settings(uuid) to service_role;

create or replace function public.set_market_tax_rate(
  p_market_id uuid,
  p_rate_percent numeric,
  p_admin_user_id uuid,
  p_reason text default null
)
returns numeric
language sql
security definer
set search_path = ''
as $$
  select private.set_market_tax_rate($1,$2,$3,$4);
$$;

revoke all on function public.set_market_tax_rate(uuid,numeric,uuid,text)
  from public, anon, authenticated;
grant execute on function public.set_market_tax_rate(uuid,numeric,uuid,text) to service_role;