create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  market_id uuid not null references public.markets(id),
  customer_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'received',
  payment_status text not null default 'pending',
  currency_code text not null,
  subtotal_before_promotions numeric not null,
  promotion_discount_total numeric not null default 0,
  coupon_discount_total numeric not null default 0,
  merchandise_subtotal numeric not null,
  shipping_fee numeric not null,
  final_total numeric not null,
  coupon_id uuid references public.coupons(id) on delete set null,
  coupon_code_snapshot text,
  idempotency_scope text not null,
  idempotency_key text not null,
  guest_access_token_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_money_non_negative check (
    subtotal_before_promotions >= 0 and
    promotion_discount_total >= 0 and
    coupon_discount_total >= 0 and
    merchandise_subtotal >= 0 and
    shipping_fee >= 0 and
    final_total >= 0
  ),
  constraint orders_guest_access_guard check (
    customer_user_id is not null or guest_access_token_hash is not null
  ),
  constraint orders_idempotency_unique unique (idempotency_scope, idempotency_key)
);

create table public.order_customer_details (
  order_id uuid primary key references public.orders(id) on delete cascade,
  recipient_name text not null,
  email text not null,
  phone text not null,
  country_code text not null,
  administrative_area text not null,
  city text not null,
  address_line1 text not null,
  delivery_notes text,
  created_at timestamptz not null default now()
);

create table public.order_artisan_groups (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  artisan_id uuid not null references public.artisan_profiles(id),
  fulfillment_status text not null default 'received',
  merchandise_subtotal numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_artisan_groups_subtotal_non_negative check (merchandise_subtotal >= 0),
  constraint order_artisan_groups_order_artisan_unique unique (order_id, artisan_id)
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  artisan_group_id uuid not null references public.order_artisan_groups(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  artisan_id uuid not null references public.artisan_profiles(id),
  craft_id uuid not null references public.crafts(id),
  product_slug_snapshot text not null,
  product_name_ar_snapshot text,
  product_name_en_snapshot text not null,
  quantity integer not null,
  unit_price numeric not null,
  original_line_total numeric not null,
  promotion_id uuid references public.promotions(id) on delete set null,
  promotion_discount numeric not null default 0,
  promotion_funding_irth numeric not null default 0,
  promotion_funding_artisan numeric not null default 0,
  coupon_discount numeric not null default 0,
  coupon_funding_irth numeric not null default 0,
  coupon_funding_artisan numeric not null default 0,
  line_total numeric not null,
  commission_rate_percent numeric(5,2) not null,
  created_at timestamptz not null default now(),
  constraint order_items_quantity_positive check (quantity > 0),
  constraint order_items_money_non_negative check (
    unit_price >= 0 and
    original_line_total >= 0 and
    promotion_discount >= 0 and
    promotion_funding_irth >= 0 and
    promotion_funding_artisan >= 0 and
    coupon_discount >= 0 and
    coupon_funding_irth >= 0 and
    coupon_funding_artisan >= 0 and
    line_total >= 0
  ),
  constraint order_items_commission_rate_range check (
    commission_rate_percent >= 0 and commission_rate_percent <= 100
  )
);

create table public.shipments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  artisan_group_id uuid not null references public.order_artisan_groups(id) on delete cascade,
  status text not null default 'pending',
  courier_code text,
  tracking_number text,
  tracking_url text,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  source text not null default 'system',
  created_at timestamptz not null default now()
);

alter table public.coupon_redemptions
  add column order_id uuid references public.orders(id) on delete restrict,
  add column guest_identity_hash text;

alter table public.coupon_redemptions
  add constraint coupon_redemptions_order_unique unique (order_id),
  add constraint coupon_redemptions_identity_required check (
    customer_user_id is not null or guest_identity_hash is not null
  );

create index orders_customer_user_id_idx on public.orders(customer_user_id);
create index orders_created_at_idx on public.orders(created_at desc);
create index order_artisan_groups_order_id_idx on public.order_artisan_groups(order_id);
create index order_artisan_groups_artisan_id_idx on public.order_artisan_groups(artisan_id);
create index order_items_order_id_idx on public.order_items(order_id);
create index order_items_artisan_group_id_idx on public.order_items(artisan_group_id);
create index order_items_product_id_idx on public.order_items(product_id);
create index shipments_order_id_idx on public.shipments(order_id);
create index shipments_artisan_group_id_idx on public.shipments(artisan_group_id);
create index order_status_history_order_id_created_at_idx on public.order_status_history(order_id, created_at);
create index coupon_redemptions_guest_identity_hash_idx on public.coupon_redemptions(guest_identity_hash);

alter table public.orders enable row level security;
alter table public.order_customer_details enable row level security;
alter table public.order_artisan_groups enable row level security;
alter table public.order_items enable row level security;
alter table public.shipments enable row level security;
alter table public.order_status_history enable row level security;

revoke all on public.orders from anon, authenticated;
revoke all on public.order_customer_details from anon, authenticated;
revoke all on public.order_artisan_groups from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
revoke all on public.shipments from anon, authenticated;
revoke all on public.order_status_history from anon, authenticated;

grant select on public.orders to authenticated;
grant select on public.order_customer_details to authenticated;
grant select on public.order_artisan_groups to authenticated;
grant select on public.order_items to authenticated;
grant select on public.shipments to authenticated;
grant select on public.order_status_history to authenticated;

create policy "Customers can read own orders"
on public.orders
for select
to authenticated
using ((select auth.uid()) = customer_user_id);

create policy "Super admin can read all orders"
on public.orders
for select
to authenticated
using ((select private.is_super_admin()));

create policy "Customers can read own order customer details"
on public.order_customer_details
for select
to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_customer_details.order_id
      and o.customer_user_id = (select auth.uid())
  )
);

create policy "Super admin can read all order customer details"
on public.order_customer_details
for select
to authenticated
using ((select private.is_super_admin()));

create policy "Customers can read own artisan groups"
on public.order_artisan_groups
for select
to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_artisan_groups.order_id
      and o.customer_user_id = (select auth.uid())
  )
);

create policy "Super admin can read all artisan groups"
on public.order_artisan_groups
for select
to authenticated
using ((select private.is_super_admin()));

create policy "Customers can read own order items"
on public.order_items
for select
to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_items.order_id
      and o.customer_user_id = (select auth.uid())
  )
);

create policy "Super admin can read all order items"
on public.order_items
for select
to authenticated
using ((select private.is_super_admin()));

create policy "Customers can read own shipments"
on public.shipments
for select
to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = shipments.order_id
      and o.customer_user_id = (select auth.uid())
  )
);

create policy "Super admin can read all shipments"
on public.shipments
for select
to authenticated
using ((select private.is_super_admin()));

create policy "Customers can read own order status history"
on public.order_status_history
for select
to authenticated
using (
  exists (
    select 1 from public.orders o
    where o.id = order_status_history.order_id
      and o.customer_user_id = (select auth.uid())
  )
);

create policy "Super admin can read all order status history"
on public.order_status_history
for select
to authenticated
using ((select private.is_super_admin()));

create or replace function public.create_order_transaction(
  p_order jsonb,
  p_customer jsonb,
  p_items jsonb,
  p_idempotency_scope text,
  p_idempotency_key text,
  p_guest_access_token_hash text default null
)
returns table(order_id uuid, order_number text, reused boolean)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_existing public.orders%rowtype;
  v_order_id uuid := gen_random_uuid();
  v_order_number text;
  v_market_id uuid;
  v_currency_code text;
  v_customer_user_id uuid;
  v_coupon_id uuid;
  v_coupon_code text;
  v_guest_identity_hash text;
  v_subtotal_before_promotions numeric;
  v_promotion_discount_total numeric;
  v_coupon_discount_total numeric;
  v_merchandise_subtotal numeric;
  v_shipping_fee numeric;
  v_final_total numeric;
  v_flat_shipping_fee numeric;
  v_free_shipping_threshold numeric;
  v_expected_shipping numeric;
  v_item jsonb;
  v_product record;
  v_quantity integer;
  v_unit_price numeric;
  v_original_line_total numeric;
  v_promotion_discount numeric;
  v_coupon_discount numeric;
  v_line_total numeric;
  v_promotion_funding_irth numeric;
  v_promotion_funding_artisan numeric;
  v_coupon_funding_irth numeric;
  v_coupon_funding_artisan numeric;
  v_promotion_id uuid;
  v_commission_rate numeric;
  v_group_id uuid;
  v_sum_original numeric := 0;
  v_sum_promotion numeric := 0;
  v_sum_coupon numeric := 0;
  v_sum_line numeric := 0;
  v_coupon public.coupons%rowtype;
  v_usage_count integer;
  v_customer_usage_count integer;
begin
  if p_idempotency_scope is null or length(trim(p_idempotency_scope)) < 3 or
     p_idempotency_key is null or length(trim(p_idempotency_key)) < 8 then
    raise exception 'invalid_idempotency';
  end if;

  select * into v_existing
  from public.orders
  where idempotency_scope = p_idempotency_scope
    and idempotency_key = p_idempotency_key
  limit 1;

  if found then
    return query select v_existing.id, v_existing.order_number, true;
    return;
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'invalid_order_items';
  end if;

  v_market_id := nullif(p_order->>'marketId','')::uuid;
  v_currency_code := upper(trim(p_order->>'currencyCode'));
  v_customer_user_id := nullif(p_order->>'customerUserId','')::uuid;
  v_coupon_id := nullif(p_order->>'couponId','')::uuid;
  v_coupon_code := nullif(trim(p_order->>'couponCode'),'');
  v_guest_identity_hash := nullif(trim(p_order->>'guestIdentityHash'),'');
  v_subtotal_before_promotions := (p_order->>'subtotalBeforePromotions')::numeric;
  v_promotion_discount_total := (p_order->>'promotionDiscountTotal')::numeric;
  v_coupon_discount_total := (p_order->>'couponDiscountTotal')::numeric;
  v_merchandise_subtotal := (p_order->>'merchandiseSubtotal')::numeric;
  v_shipping_fee := (p_order->>'shippingFee')::numeric;
  v_final_total := (p_order->>'finalTotal')::numeric;

  if v_customer_user_id is null and (p_guest_access_token_hash is null or length(trim(p_guest_access_token_hash)) < 32) then
    raise exception 'guest_access_token_required';
  end if;

  perform 1
  from public.markets m
  where m.id = v_market_id
    and m.is_active = true
    and m.currency_code = v_currency_code
  for share;

  if not found then
    raise exception 'market_changed';
  end if;

  select s.flat_shipping_fee, s.free_shipping_threshold
  into v_flat_shipping_fee, v_free_shipping_threshold
  from public.market_shipping_settings s
  where s.market_id = v_market_id
  for share;

  if not found then
    raise exception 'shipping_configuration_missing';
  end if;

  v_expected_shipping := case
    when v_merchandise_subtotal >= v_free_shipping_threshold then 0
    else v_flat_shipping_fee
  end;

  if v_shipping_fee <> v_expected_shipping or
     v_final_total <> v_merchandise_subtotal + v_shipping_fee or
     v_merchandise_subtotal <> v_subtotal_before_promotions - v_promotion_discount_total - v_coupon_discount_total then
    raise exception 'order_totals_changed';
  end if;

  if v_coupon_id is not null then
    select * into v_coupon
    from public.coupons c
    where c.id = v_coupon_id
    for update;

    if not found or
       v_coupon.market_id <> v_market_id or
       v_coupon.is_enabled is not true or
       now() < v_coupon.start_at or now() >= v_coupon.end_at or
       upper(trim(v_coupon.code)) <> upper(trim(coalesce(v_coupon_code,''))) then
      raise exception 'coupon_changed';
    end if;

    select count(*)::int into v_usage_count
    from public.coupon_redemptions cr
    where cr.coupon_id = v_coupon_id;

    if v_coupon.total_usage_limit is not null and v_usage_count >= v_coupon.total_usage_limit then
      raise exception 'coupon_usage_exhausted';
    end if;

    if v_coupon.per_customer_usage_limit is not null then
      if v_customer_user_id is not null then
        select count(*)::int into v_customer_usage_count
        from public.coupon_redemptions cr
        where cr.coupon_id = v_coupon_id
          and cr.customer_user_id = v_customer_user_id;
      else
        if v_guest_identity_hash is null then
          raise exception 'guest_coupon_identity_required';
        end if;
        select count(*)::int into v_customer_usage_count
        from public.coupon_redemptions cr
        where cr.coupon_id = v_coupon_id
          and cr.guest_identity_hash = v_guest_identity_hash;
      end if;

      if v_customer_usage_count >= v_coupon.per_customer_usage_limit then
        raise exception 'coupon_customer_limit_reached';
      end if;
    end if;
  elsif v_coupon_discount_total <> 0 then
    raise exception 'coupon_snapshot_missing';
  end if;

  v_order_number := 'IRTH-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' || upper(substr(replace(v_order_id::text, '-', ''), 1, 8));

  insert into public.orders (
    id, order_number, market_id, customer_user_id, status, payment_status,
    currency_code, subtotal_before_promotions, promotion_discount_total,
    coupon_discount_total, merchandise_subtotal, shipping_fee, final_total,
    coupon_id, coupon_code_snapshot, idempotency_scope, idempotency_key,
    guest_access_token_hash
  ) values (
    v_order_id, v_order_number, v_market_id, v_customer_user_id, 'received', 'pending',
    v_currency_code, v_subtotal_before_promotions, v_promotion_discount_total,
    v_coupon_discount_total, v_merchandise_subtotal, v_shipping_fee, v_final_total,
    v_coupon_id, v_coupon_code, trim(p_idempotency_scope), trim(p_idempotency_key),
    nullif(trim(p_guest_access_token_hash),'')
  );

  insert into public.order_customer_details (
    order_id, recipient_name, email, phone, country_code,
    administrative_area, city, address_line1, delivery_notes
  ) values (
    v_order_id,
    trim(p_customer->>'recipientName'),
    lower(trim(p_customer->>'email')),
    trim(p_customer->>'phone'),
    upper(trim(p_customer->>'countryCode')),
    trim(p_customer->>'administrativeArea'),
    trim(p_customer->>'city'),
    trim(p_customer->>'addressLine1'),
    nullif(trim(p_customer->>'deliveryNotes'),'')
  );

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := (v_item->>'quantity')::integer;
    v_unit_price := (v_item->>'unitPrice')::numeric;
    v_original_line_total := (v_item->>'originalLineTotal')::numeric;
    v_promotion_discount := coalesce((v_item->>'promotionDiscount')::numeric, 0);
    v_coupon_discount := coalesce((v_item->>'couponDiscount')::numeric, 0);
    v_line_total := (v_item->>'lineTotal')::numeric;
    v_promotion_funding_irth := coalesce((v_item->>'promotionFundingIrth')::numeric, 0);
    v_promotion_funding_artisan := coalesce((v_item->>'promotionFundingArtisan')::numeric, 0);
    v_coupon_funding_irth := coalesce((v_item->>'couponFundingIrth')::numeric, 0);
    v_coupon_funding_artisan := coalesce((v_item->>'couponFundingArtisan')::numeric, 0);
    v_promotion_id := nullif(v_item->>'promotionId','')::uuid;

    if v_quantity <= 0 or
       v_unit_price < 0 or
       v_original_line_total <> v_unit_price * v_quantity or
       v_line_total <> v_original_line_total - v_promotion_discount - v_coupon_discount or
       v_promotion_funding_irth + v_promotion_funding_artisan <> v_promotion_discount or
       v_coupon_funding_irth + v_coupon_funding_artisan <> v_coupon_discount then
      raise exception 'order_item_totals_changed';
    end if;

    select
      p.id,
      p.slug,
      p.name_ar,
      p.name_en,
      p.artisan_id,
      p.primary_craft_id,
      p.made_to_order,
      p.quantity as stock_quantity,
      p.lifecycle_status,
      pmp.price as market_price
    into v_product
    from public.products p
    join public.product_market_prices pmp
      on pmp.product_id = p.id
     and pmp.market_id = v_market_id
     and pmp.is_active = true
    join public.artisan_profiles a
      on a.id = p.artisan_id
     and a.status = 'active'
    join public.crafts c
      on c.id = p.primary_craft_id
     and c.is_active = true
    join public.countries co
      on co.id = a.country_id
     and co.is_active = true
    where p.id = nullif(v_item->>'productId','')::uuid
      and p.lifecycle_status = 'published'
    for update of p, pmp;

    if not found or v_product.market_price <> v_unit_price then
      raise exception 'product_or_price_changed';
    end if;

    if v_promotion_id is not null then
      perform 1
      from public.promotions pr
      join public.promotion_products pp on pp.promotion_id = pr.id
      where pr.id = v_promotion_id
        and pp.product_id = v_product.id
        and pr.market_id = v_market_id
        and pr.approval_status = 'approved'
        and pr.is_enabled = true
        and now() >= pr.start_at and now() < pr.end_at
      for share of pr;

      if not found then
        raise exception 'promotion_changed';
      end if;
    elsif v_promotion_discount <> 0 then
      raise exception 'promotion_snapshot_missing';
    end if;

    select coalesce(aco.rate_percent, ccr.rate_percent)
    into v_commission_rate
    from (select 1) base
    left join public.artisan_commission_overrides aco
      on aco.artisan_id = v_product.artisan_id
    left join public.craft_commission_rates ccr
      on ccr.craft_id = v_product.primary_craft_id;

    if v_commission_rate is null then
      raise exception 'commission_not_configured';
    end if;

    if not v_product.made_to_order then
      if v_product.stock_quantity is null or v_product.stock_quantity < v_quantity then
        raise exception 'insufficient_stock';
      end if;

      update public.products
      set quantity = quantity - v_quantity,
          updated_at = now()
      where id = v_product.id;
    end if;

    select g.id into v_group_id
    from public.order_artisan_groups g
    where g.order_id = v_order_id
      and g.artisan_id = v_product.artisan_id;

    if not found then
      insert into public.order_artisan_groups(order_id, artisan_id, fulfillment_status)
      values (v_order_id, v_product.artisan_id, 'received')
      returning id into v_group_id;
    end if;

    insert into public.order_items (
      order_id, artisan_group_id, product_id, artisan_id, craft_id,
      product_slug_snapshot, product_name_ar_snapshot, product_name_en_snapshot,
      quantity, unit_price, original_line_total, promotion_id,
      promotion_discount, promotion_funding_irth, promotion_funding_artisan,
      coupon_discount, coupon_funding_irth, coupon_funding_artisan,
      line_total, commission_rate_percent
    ) values (
      v_order_id, v_group_id, v_product.id, v_product.artisan_id, v_product.primary_craft_id,
      v_product.slug, v_product.name_ar, v_product.name_en,
      v_quantity, v_unit_price, v_original_line_total, v_promotion_id,
      v_promotion_discount, v_promotion_funding_irth, v_promotion_funding_artisan,
      v_coupon_discount, v_coupon_funding_irth, v_coupon_funding_artisan,
      v_line_total, v_commission_rate
    );

    v_sum_original := v_sum_original + v_original_line_total;
    v_sum_promotion := v_sum_promotion + v_promotion_discount;
    v_sum_coupon := v_sum_coupon + v_coupon_discount;
    v_sum_line := v_sum_line + v_line_total;
  end loop;

  if v_sum_original <> v_subtotal_before_promotions or
     v_sum_promotion <> v_promotion_discount_total or
     v_sum_coupon <> v_coupon_discount_total or
     v_sum_line <> v_merchandise_subtotal then
    raise exception 'order_aggregate_totals_changed';
  end if;

  update public.order_artisan_groups g
  set merchandise_subtotal = totals.subtotal,
      updated_at = now()
  from (
    select oi.artisan_group_id, sum(oi.line_total) as subtotal
    from public.order_items oi
    where oi.order_id = v_order_id
    group by oi.artisan_group_id
  ) totals
  where g.id = totals.artisan_group_id;

  if v_coupon_id is not null then
    insert into public.coupon_redemptions (
      coupon_id, customer_user_id, order_id, guest_identity_hash, consumed_at
    ) values (
      v_coupon_id, v_customer_user_id, v_order_id,
      case when v_customer_user_id is null then v_guest_identity_hash else null end,
      now()
    );
  end if;

  insert into public.order_status_history(order_id, status, changed_by, source)
  values (v_order_id, 'received', v_customer_user_id, 'order_creation');

  return query select v_order_id, v_order_number, false;
end;
$$;

revoke all on function public.create_order_transaction(jsonb,jsonb,jsonb,text,text,text) from public, anon, authenticated;
grant execute on function public.create_order_transaction(jsonb,jsonb,jsonb,text,text,text) to service_role;