create table if not exists public.shipment_tracking_history (
  id bigint generated by default as identity primary key,
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  old_courier_code text,
  new_courier_code text,
  old_tracking_number text,
  new_tracking_number text,
  old_tracking_url text,
  new_tracking_url text,
  changed_by_user_id uuid references auth.users(id) on delete set null,
  source text not null default 'admin',
  created_at timestamptz not null default now()
);

alter table public.shipment_tracking_history enable row level security;
revoke all on table public.shipment_tracking_history from public, anon, authenticated;
revoke all on sequence public.shipment_tracking_history_id_seq from public, anon, authenticated;

create index if not exists shipment_tracking_history_shipment_created_idx
  on public.shipment_tracking_history (shipment_id, created_at desc);

create or replace function private.update_admin_shipment_tracking(
  p_shipment_id uuid,
  p_courier_code text,
  p_tracking_number text,
  p_tracking_url text
)
returns table (
  shipment_id uuid,
  order_id uuid,
  courier_code text,
  tracking_number text,
  tracking_url text,
  changed boolean,
  changed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_user_id uuid := (select auth.uid());
  v_order_id uuid;
  v_old_courier_code text;
  v_old_tracking_number text;
  v_old_tracking_url text;
  v_courier_code text := nullif(lower(trim(coalesce(p_courier_code, ''))), '');
  v_tracking_number text := nullif(trim(coalesce(p_tracking_number, '')), '');
  v_tracking_url text := nullif(trim(coalesce(p_tracking_url, '')), '');
  v_changed_at timestamptz := now();
begin
  if v_user_id is null or not (select private.is_super_admin()) then
    raise exception 'admin_required' using errcode = '42501';
  end if;

  if p_shipment_id is null then
    raise exception 'shipment_required';
  end if;

  if v_courier_code is not null and (
    length(v_courier_code) > 64 or v_courier_code !~ '^[a-z0-9][a-z0-9_-]*$'
  ) then
    raise exception 'invalid_courier_code';
  end if;

  if v_tracking_number is not null and (
    length(v_tracking_number) > 128 or v_tracking_number ~ '[[:cntrl:]]'
  ) then
    raise exception 'invalid_tracking_number';
  end if;

  if v_tracking_url is not null and (
    length(v_tracking_url) > 2048 or v_tracking_url !~* '^https://[^[:space:]]+$'
  ) then
    raise exception 'invalid_tracking_url';
  end if;

  select s.order_id, s.courier_code, s.tracking_number, s.tracking_url
    into v_order_id, v_old_courier_code, v_old_tracking_number, v_old_tracking_url
  from public.shipments s
  where s.id = p_shipment_id
  for update;

  if not found then
    raise exception 'shipment_not_found';
  end if;

  if v_old_courier_code is not distinct from v_courier_code
     and v_old_tracking_number is not distinct from v_tracking_number
     and v_old_tracking_url is not distinct from v_tracking_url then
    return query
    select p_shipment_id, v_order_id, v_old_courier_code, v_old_tracking_number, v_old_tracking_url, false, null::timestamptz;
    return;
  end if;

  update public.shipments
  set courier_code = v_courier_code,
      tracking_number = v_tracking_number,
      tracking_url = v_tracking_url,
      updated_at = v_changed_at
  where id = p_shipment_id;

  insert into public.shipment_tracking_history (
    shipment_id,
    order_id,
    old_courier_code,
    new_courier_code,
    old_tracking_number,
    new_tracking_number,
    old_tracking_url,
    new_tracking_url,
    changed_by_user_id,
    source,
    created_at
  ) values (
    p_shipment_id,
    v_order_id,
    v_old_courier_code,
    v_courier_code,
    v_old_tracking_number,
    v_tracking_number,
    v_old_tracking_url,
    v_tracking_url,
    v_user_id,
    'admin',
    v_changed_at
  );

  return query
  select p_shipment_id, v_order_id, v_courier_code, v_tracking_number, v_tracking_url, true, v_changed_at;
end;
$function$;

revoke all on function private.update_admin_shipment_tracking(uuid, text, text, text) from public;
grant execute on function private.update_admin_shipment_tracking(uuid, text, text, text) to authenticated;

create or replace function public.update_admin_shipment_tracking(
  p_shipment_id uuid,
  p_courier_code text,
  p_tracking_number text,
  p_tracking_url text
)
returns table (
  shipment_id uuid,
  order_id uuid,
  courier_code text,
  tracking_number text,
  tracking_url text,
  changed boolean,
  changed_at timestamptz
)
language sql
security invoker
set search_path = ''
as $function$
  select *
  from private.update_admin_shipment_tracking(
    p_shipment_id,
    p_courier_code,
    p_tracking_number,
    p_tracking_url
  );
$function$;

revoke all on function public.update_admin_shipment_tracking(uuid, text, text, text) from public, anon;
grant execute on function public.update_admin_shipment_tracking(uuid, text, text, text) to authenticated;
