-- M2.1 — Provider-independent Payment Database + Audit Foundation
-- Approved 31 August 2026.

-- Keep Order payment_status as a constrained summary only.
do $$
begin
  if exists (
    select 1
    from public.orders
    where payment_status not in ('pending', 'paid', 'cancelled')
  ) then
    raise exception 'unsupported_existing_order_payment_status';
  end if;
end;
$$;

alter table public.orders
  add constraint orders_payment_status_core_values
  check (payment_status in ('pending', 'paid', 'cancelled'));

create table private.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete restrict,
  method text,
  status text not null default 'pending',
  amount numeric not null,
  currency_code text not null,
  currency_minor_unit_scale smallint not null,
  paid_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payments_method_values check (method is null or method in ('online', 'cod')),
  constraint payments_status_values check (status in ('pending', 'paid', 'cancelled')),
  constraint payments_amount_non_negative check (amount >= 0),
  constraint payments_currency_code_format check (currency_code ~ '^[A-Z]{3}$'),
  constraint payments_currency_scale_range check (currency_minor_unit_scale between 0 and 6),
  constraint payments_paid_at_consistency check ((status = 'paid') = (paid_at is not null)),
  constraint payments_cancelled_at_consistency check ((status = 'cancelled') = (cancelled_at is not null)),
  constraint payments_terminal_timestamp_exclusive check (not (paid_at is not null and cancelled_at is not null))
);

create table private.payment_attempts (
  id uuid primary key default gen_random_uuid(),
  payment_id uuid not null references private.payments(id) on delete restrict,
  attempt_number integer not null,
  status text not null default 'created',
  provider_code text,
  provider_reference text,
  amount numeric not null,
  currency_code text not null,
  currency_minor_unit_scale smallint not null,
  expires_at timestamptz,
  succeeded_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_attempts_number_positive check (attempt_number > 0),
  constraint payment_attempts_status_values check (status in ('created', 'pending', 'succeeded', 'failed', 'expired', 'cancelled')),
  constraint payment_attempts_amount_non_negative check (amount >= 0),
  constraint payment_attempts_currency_code_format check (currency_code ~ '^[A-Z]{3}$'),
  constraint payment_attempts_currency_scale_range check (currency_minor_unit_scale between 0 and 6),
  constraint payment_attempts_payment_number_unique unique (payment_id, attempt_number),
  constraint payment_attempts_succeeded_at_consistency check ((status = 'succeeded') = (succeeded_at is not null)),
  constraint payment_attempts_failed_at_consistency check ((status = 'failed') = (failed_at is not null)),
  constraint payment_attempts_terminal_timestamp_exclusive check (not (succeeded_at is not null and failed_at is not null))
);

create unique index payment_attempts_provider_reference_unique
on private.payment_attempts(provider_code, provider_reference)
where provider_code is not null and provider_reference is not null;

create table private.payment_events (
  id bigint generated by default as identity primary key,
  payment_id uuid not null references private.payments(id) on delete restrict,
  payment_attempt_id uuid references private.payment_attempts(id) on delete restrict,
  event_type text not null,
  event_source text not null,
  source_key text not null unique,
  provider_code text,
  provider_event_id text,
  amount numeric,
  currency_code text,
  metadata jsonb not null default '{}'::jsonb,
  recorded_by_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint payment_events_event_type_nonblank check (length(trim(event_type)) >= 3),
  constraint payment_events_source_values check (event_source in ('system', 'provider', 'admin')),
  constraint payment_events_source_key_nonblank check (length(trim(source_key)) >= 8),
  constraint payment_events_amount_non_negative check (amount is null or amount >= 0),
  constraint payment_events_currency_code_format check (currency_code is null or currency_code ~ '^[A-Z]{3}$'),
  constraint payment_events_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create unique index payment_events_provider_event_unique
on private.payment_events(provider_code, provider_event_id)
where provider_code is not null and provider_event_id is not null;

create index payments_status_idx on private.payments(status);
create index payment_attempts_payment_status_idx on private.payment_attempts(payment_id, status);
create index payment_events_payment_created_idx on private.payment_events(payment_id, created_at);
create index payment_events_attempt_created_idx on private.payment_events(payment_attempt_id, created_at)
where payment_attempt_id is not null;

-- Private domain: no direct Browser or service-role table writes.
revoke all on private.payments from public, anon, authenticated, service_role;
revoke all on private.payment_attempts from public, anon, authenticated, service_role;
revoke all on private.payment_events from public, anon, authenticated, service_role;

grant select on private.payments to service_role;
grant select on private.payment_attempts to service_role;
grant select on private.payment_events to service_role;

-- Append-only event history: corrections must be new events.
create or replace function private.prevent_payment_event_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'payment_events_are_append_only';
end;
$$;

revoke all on function private.prevent_payment_event_mutation() from public, anon, authenticated, service_role;

create trigger payment_events_prevent_update_delete
before update or delete on private.payment_events
for each row
execute function private.prevent_payment_event_mutation();

-- Backfill one Payment summary per existing Order without inventing a historical method.
insert into private.payments (
  order_id,
  method,
  status,
  amount,
  currency_code,
  currency_minor_unit_scale,
  paid_at,
  cancelled_at,
  created_at,
  updated_at
)
select
  o.id,
  null,
  o.payment_status,
  o.final_total,
  o.currency_code,
  m.currency_minor_unit_scale,
  case when o.payment_status = 'paid' then o.created_at else null end,
  case when o.payment_status = 'cancelled' then o.created_at else null end,
  o.created_at,
  now()
from public.orders o
join public.markets m on m.id = o.market_id;

insert into private.payment_events (
  payment_id,
  event_type,
  event_source,
  source_key,
  amount,
  currency_code,
  metadata,
  created_at
)
select
  p.id,
  'payment_core_backfill',
  'system',
  'payment-core-backfill:' || p.order_id::text,
  p.amount,
  p.currency_code,
  jsonb_build_object('legacy_method_unknown', true, 'order_payment_status', p.status),
  p.created_at
from private.payments p;
