-- M1.1 — Commission Settlement Ledger Foundation
-- Approved 31 August 2026.
--
-- Financial rule:
-- - Artisan-funded discounts reduce the artisan settlement / commission base.
-- - IRTH-funded discounts do not reduce artisan economic entitlement or commission base.
-- - Sale settlement is represented as append-only ledger entries.
-- - Currency rounding is market-configured and fails closed when missing.

alter table public.markets
  add column currency_minor_unit_scale smallint;

update public.markets
set currency_minor_unit_scale = 2
where currency_code = 'EGP';

do $$
begin
  if exists (
    select 1
    from public.markets
    where currency_minor_unit_scale is null
  ) then
    raise exception 'currency_minor_unit_scale_missing_for_existing_market';
  end if;
end;
$$;

alter table public.markets
  alter column currency_minor_unit_scale set not null,
  add constraint markets_currency_minor_unit_scale_range
    check (currency_minor_unit_scale between 0 and 6);

alter table public.order_items
  add constraint order_items_promotion_funding_split_matches
    check (promotion_discount = promotion_funding_irth + promotion_funding_artisan),
  add constraint order_items_coupon_funding_split_matches
    check (coupon_discount = coupon_funding_irth + coupon_funding_artisan),
  add constraint order_items_line_total_matches_discount_snapshots
    check (line_total = original_line_total - promotion_discount - coupon_discount);

create table private.artisan_settlement_ledger (
  id bigint generated by default as identity primary key,
  entry_key text not null unique,
  order_id uuid not null references public.orders(id) on delete restrict,
  order_item_id uuid not null references public.order_items(id) on delete restrict,
  artisan_group_id uuid not null references public.order_artisan_groups(id) on delete restrict,
  artisan_id uuid not null references public.artisan_profiles(id) on delete restrict,
  currency_code text not null,
  currency_minor_unit_scale smallint not null,
  entry_type text not null,
  amount numeric not null,
  calculation_base_amount numeric,
  rate_percent numeric(5,2),
  source text not null default 'order_item_sale',
  reason text,
  reference_code text,
  recorded_by_user_id uuid references auth.users(id) on delete set null,
  effective_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint artisan_settlement_ledger_entry_key_not_blank
    check (length(trim(entry_key)) > 0),
  constraint artisan_settlement_ledger_entry_type_not_blank
    check (length(trim(entry_type)) > 0),
  constraint artisan_settlement_ledger_currency_code_format
    check (currency_code ~ '^[A-Z]{3}$'),
  constraint artisan_settlement_ledger_currency_scale_range
    check (currency_minor_unit_scale between 0 and 6),
  constraint artisan_settlement_ledger_rate_range
    check (rate_percent is null or (rate_percent >= 0 and rate_percent <= 100)),
  constraint artisan_settlement_ledger_amount_currency_scale
    check (amount = round(amount, currency_minor_unit_scale)),
  constraint artisan_settlement_ledger_base_currency_scale
    check (
      calculation_base_amount is null or
      calculation_base_amount = round(calculation_base_amount, currency_minor_unit_scale)
    ),
  constraint artisan_settlement_ledger_sale_entry_signs
    check (
      (entry_type not in ('merchandise_proceeds', 'irth_discount_subsidy') or amount >= 0)
      and
      (entry_type <> 'commission' or amount <= 0)
    ),
  constraint artisan_settlement_ledger_commission_context
    check (
      entry_type <> 'commission' or
      (calculation_base_amount is not null and rate_percent is not null)
    )
);

create index artisan_settlement_ledger_order_id_idx
  on private.artisan_settlement_ledger(order_id, created_at);
create index artisan_settlement_ledger_order_item_id_idx
  on private.artisan_settlement_ledger(order_item_id);
create index artisan_settlement_ledger_artisan_group_id_idx
  on private.artisan_settlement_ledger(artisan_group_id);
create index artisan_settlement_ledger_artisan_id_idx
  on private.artisan_settlement_ledger(artisan_id, created_at);
create index artisan_settlement_ledger_recorded_by_user_id_idx
  on private.artisan_settlement_ledger(recorded_by_user_id)
  where recorded_by_user_id is not null;

revoke all on table private.artisan_settlement_ledger
  from public, anon, authenticated;
revoke all on sequence private.artisan_settlement_ledger_id_seq
  from public, anon, authenticated;
grant select on table private.artisan_settlement_ledger
  to service_role;

create or replace function private.reject_artisan_settlement_ledger_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception 'artisan_settlement_ledger_is_append_only';
end;
$$;

revoke all on function private.reject_artisan_settlement_ledger_mutation()
  from public, anon, authenticated, service_role;

create trigger artisan_settlement_ledger_append_only
before update or delete on private.artisan_settlement_ledger
for each row
execute function private.reject_artisan_settlement_ledger_mutation();

create or replace function private.create_order_item_sale_settlement_entries()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_currency_code text;
  v_currency_scale smallint;
  v_commissionable_amount numeric;
  v_commission_amount numeric;
  v_irth_discount_subsidy numeric;
begin
  select o.currency_code, m.currency_minor_unit_scale
  into v_currency_code, v_currency_scale
  from public.orders o
  join public.markets m on m.id = o.market_id
  where o.id = new.order_id;

  if not found or v_currency_scale is null then
    raise exception 'settlement_currency_configuration_missing';
  end if;

  if new.promotion_discount <> new.promotion_funding_irth + new.promotion_funding_artisan or
     new.coupon_discount <> new.coupon_funding_irth + new.coupon_funding_artisan or
     new.line_total <> new.original_line_total - new.promotion_discount - new.coupon_discount then
    raise exception 'settlement_order_item_snapshot_invalid';
  end if;

  v_irth_discount_subsidy := round(
    new.promotion_funding_irth + new.coupon_funding_irth,
    v_currency_scale
  );

  v_commissionable_amount := round(
    new.line_total + v_irth_discount_subsidy,
    v_currency_scale
  );

  v_commission_amount := round(
    v_commissionable_amount * new.commission_rate_percent / 100,
    v_currency_scale
  );

  insert into private.artisan_settlement_ledger (
    entry_key, order_id, order_item_id, artisan_group_id, artisan_id,
    currency_code, currency_minor_unit_scale, entry_type, amount,
    calculation_base_amount, rate_percent, source, reference_code, effective_at
  )
  values
    (
      'sale:' || new.id::text || ':merchandise_proceeds',
      new.order_id, new.id, new.artisan_group_id, new.artisan_id,
      v_currency_code, v_currency_scale, 'merchandise_proceeds',
      round(new.line_total, v_currency_scale),
      null, null, 'order_item_sale', new.id::text, new.created_at
    ),
    (
      'sale:' || new.id::text || ':irth_discount_subsidy',
      new.order_id, new.id, new.artisan_group_id, new.artisan_id,
      v_currency_code, v_currency_scale, 'irth_discount_subsidy',
      v_irth_discount_subsidy,
      null, null, 'order_item_sale', new.id::text, new.created_at
    ),
    (
      'sale:' || new.id::text || ':commission',
      new.order_id, new.id, new.artisan_group_id, new.artisan_id,
      v_currency_code, v_currency_scale, 'commission',
      -v_commission_amount,
      v_commissionable_amount, new.commission_rate_percent,
      'order_item_sale', new.id::text, new.created_at
    );

  return new;
end;
$$;

revoke all on function private.create_order_item_sale_settlement_entries()
  from public, anon, authenticated, service_role;

-- Backfill existing Order Items with exactly three sale-settlement entries each.
insert into private.artisan_settlement_ledger (
  entry_key, order_id, order_item_id, artisan_group_id, artisan_id,
  currency_code, currency_minor_unit_scale, entry_type, amount,
  calculation_base_amount, rate_percent, source, reference_code, effective_at
)
select
  'sale:' || oi.id::text || ':merchandise_proceeds',
  oi.order_id, oi.id, oi.artisan_group_id, oi.artisan_id,
  o.currency_code, m.currency_minor_unit_scale,
  'merchandise_proceeds',
  round(oi.line_total, m.currency_minor_unit_scale),
  null::numeric,
  null::numeric,
  'order_item_sale',
  oi.id::text,
  oi.created_at
from public.order_items oi
join public.orders o on o.id = oi.order_id
join public.markets m on m.id = o.market_id;

insert into private.artisan_settlement_ledger (
  entry_key, order_id, order_item_id, artisan_group_id, artisan_id,
  currency_code, currency_minor_unit_scale, entry_type, amount,
  calculation_base_amount, rate_percent, source, reference_code, effective_at
)
select
  'sale:' || oi.id::text || ':irth_discount_subsidy',
  oi.order_id, oi.id, oi.artisan_group_id, oi.artisan_id,
  o.currency_code, m.currency_minor_unit_scale,
  'irth_discount_subsidy',
  round(oi.promotion_funding_irth + oi.coupon_funding_irth, m.currency_minor_unit_scale),
  null::numeric,
  null::numeric,
  'order_item_sale',
  oi.id::text,
  oi.created_at
from public.order_items oi
join public.orders o on o.id = oi.order_id
join public.markets m on m.id = o.market_id;

insert into private.artisan_settlement_ledger (
  entry_key, order_id, order_item_id, artisan_group_id, artisan_id,
  currency_code, currency_minor_unit_scale, entry_type, amount,
  calculation_base_amount, rate_percent, source, reference_code, effective_at
)
select
  'sale:' || oi.id::text || ':commission',
  oi.order_id, oi.id, oi.artisan_group_id, oi.artisan_id,
  o.currency_code, m.currency_minor_unit_scale,
  'commission',
  -round(
    round(
      oi.line_total + oi.promotion_funding_irth + oi.coupon_funding_irth,
      m.currency_minor_unit_scale
    ) * oi.commission_rate_percent / 100,
    m.currency_minor_unit_scale
  ),
  round(
    oi.line_total + oi.promotion_funding_irth + oi.coupon_funding_irth,
    m.currency_minor_unit_scale
  ),
  oi.commission_rate_percent,
  'order_item_sale',
  oi.id::text,
  oi.created_at
from public.order_items oi
join public.orders o on o.id = oi.order_id
join public.markets m on m.id = o.market_id;

create trigger order_item_sale_settlement_ledger
after insert on public.order_items
for each row
execute function private.create_order_item_sale_settlement_entries();
