-- Cancellation v0.1 for the current Egypt + COD controlled beta.
-- Before preparing: customer/guest cancellation applies directly.
-- Preparing / ready for courier: IRTH review is required.
-- After courier pickup: cancellation is unavailable; Return / Refusal applies instead.
-- Online paid cancellation is intentionally not introduced here.

create table if not exists private.order_cancellation_requests (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete restrict,
  customer_user_id uuid references auth.users(id) on delete set null,
  requester_kind text not null check (requester_kind in ('authenticated_customer','guest_customer')),
  reason_text text not null check (char_length(trim(reason_text)) between 3 and 1000),
  requires_admin_review boolean not null,
  status text not null default 'requested' check (status in ('requested','approved','rejected')),
  submitted_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by_user_id uuid references auth.users(id) on delete set null,
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_cancellation_resolution_consistency check (
    (status='requested' and resolved_at is null and resolved_by_user_id is null)
    or
    (status in ('approved','rejected') and resolved_at is not null and (
      (requires_admin_review and resolved_by_user_id is not null)
      or not requires_admin_review
    ))
  )
);

create unique index if not exists order_cancellation_one_pending_per_order
  on private.order_cancellation_requests(order_id)
  where status='requested';
create index if not exists order_cancellation_requests_order_idx
  on private.order_cancellation_requests(order_id, submitted_at desc);

create table if not exists private.order_cancellation_events (
  id bigint generated by default as identity primary key,
  cancellation_request_id uuid not null references private.order_cancellation_requests(id) on delete restrict,
  order_id uuid not null references public.orders(id) on delete restrict,
  event_type text not null check (char_length(trim(event_type)) >= 3),
  event_source text not null check (event_source in ('customer','admin','system')),
  actor_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  created_at timestamptz not null default now()
);
create index if not exists order_cancellation_events_request_idx
  on private.order_cancellation_events(cancellation_request_id, created_at);

revoke all on private.order_cancellation_requests from public, anon, authenticated;
revoke all on private.order_cancellation_events from public, anon, authenticated;
grant select on private.order_cancellation_requests to service_role;
grant select on private.order_cancellation_events to service_role;

create or replace function private.cancel_pending_cod_order(
  p_order_id uuid,
  p_request_id uuid,
  p_actor_user_id uuid,
  p_source text
)
returns table(order_id uuid, order_status text, payment_status text, restored_quantity integer, changed boolean)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_order public.orders%rowtype;
  v_payment private.payments%rowtype;
  v_now timestamptz := now();
  v_restored integer := 0;
  v_event_source text := case when coalesce(p_source,'') like 'admin_%' then 'admin' else 'system' end;
begin
  select o.* into v_order from public.orders o where o.id=p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;

  select p.* into v_payment from private.payments p where p.order_id=p_order_id for update;
  if not found then raise exception 'payment_not_found'; end if;

  if v_order.status='cancelled' and v_payment.status='cancelled' then
    return query select v_order.id,'cancelled'::text,'cancelled'::text,0,false;
    return;
  end if;

  if v_payment.method<>'cod' then raise exception 'cod_cancellation_beta_only'; end if;
  if v_payment.status<>'pending' then raise exception 'pending_cod_payment_required'; end if;
  if v_order.status not in ('received','confirmed','preparing','ready_for_courier_pickup') then
    raise exception 'cancellation_state_not_allowed';
  end if;
  if exists (
    select 1 from public.shipments s
    where s.order_id=v_order.id and s.status<>'pending'
  ) then
    raise exception 'cancellation_unavailable_after_courier';
  end if;

  with active as (
    select r.product_id,sum(r.reserved_quantity)::integer qty
    from private.order_inventory_reservations r
    where r.order_id=v_order.id and r.released_at is null
    group by r.product_id
  ), restored as (
    update public.products pr
    set quantity=pr.quantity+active.qty,updated_at=v_now
    from active
    where pr.id=active.product_id and pr.quantity is not null
    returning active.qty
  )
  select coalesce(sum(qty),0)::integer into v_restored from restored;

  update private.order_inventory_reservations r
  set released_at=v_now,release_reason='customer_order_cancelled'
  where r.order_id=v_order.id and r.released_at is null;

  update private.payments
  set status='cancelled',cancelled_at=v_now,paid_at=null,updated_at=v_now
  where id=v_payment.id;

  update public.orders
  set payment_status='cancelled',status='cancelled',updated_at=v_now
  where id=v_order.id;

  insert into private.payment_events(
    payment_id,event_type,event_source,source_key,amount,currency_code,metadata,recorded_by_user_id
  ) values (
    v_payment.id,
    'cod_order_cancelled',
    v_event_source,
    'order-cancellation:'||p_request_id::text,
    v_payment.amount,
    v_payment.currency_code,
    jsonb_build_object('cancellation_request_id',p_request_id,'restored_quantity',v_restored,'source',p_source),
    p_actor_user_id
  );

  insert into public.order_status_history(order_id,status,changed_by,source,created_at)
  values(v_order.id,'cancelled',p_actor_user_id,coalesce(nullif(trim(p_source),''),'customer_cancellation'),v_now);

  return query select v_order.id,'cancelled'::text,'cancelled'::text,v_restored,true;
end;
$function$;

create or replace function private.create_order_cancellation_request_common(
  p_order_id uuid,
  p_requester_kind text,
  p_customer_user_id uuid,
  p_guest_access_token_hash text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_order public.orders%rowtype;
  v_payment private.payments%rowtype;
  v_existing private.order_cancellation_requests%rowtype;
  v_request private.order_cancellation_requests%rowtype;
  v_requires_review boolean;
  v_now timestamptz:=now();
  v_cancel record;
begin
  if p_order_id is null then raise exception 'order_required'; end if;
  if p_requester_kind not in ('authenticated_customer','guest_customer') then raise exception 'invalid_requester_kind'; end if;
  if char_length(trim(coalesce(p_reason,''))) not between 3 and 1000 then raise exception 'invalid_cancellation_reason'; end if;

  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;

  if p_requester_kind='authenticated_customer' then
    if p_customer_user_id is null or v_order.customer_user_id is distinct from p_customer_user_id then
      raise exception 'cancellation_order_access_denied' using errcode='42501';
    end if;
  else
    if v_order.customer_user_id is not null
       or p_guest_access_token_hash is null
       or length(trim(p_guest_access_token_hash))<32
       or v_order.guest_access_token_hash is distinct from p_guest_access_token_hash then
      raise exception 'cancellation_order_access_denied' using errcode='42501';
    end if;
  end if;

  if v_order.status='cancelled' then
    select * into v_existing
    from private.order_cancellation_requests cr
    where cr.order_id=v_order.id
    order by cr.submitted_at desc
    limit 1;
    return jsonb_build_object(
      'requestId',v_existing.id,
      'requestStatus',coalesce(v_existing.status,'approved'),
      'orderStatus','cancelled',
      'requiresAdminReview',false,
      'changed',false
    );
  end if;

  if v_order.status in ('picked_up_from_artisan','in_transit','delivered','delivery_failed','returned') then
    raise exception 'cancellation_unavailable_after_courier';
  end if;

  select * into v_payment from private.payments p where p.order_id=v_order.id for update;
  if not found then raise exception 'payment_not_found'; end if;
  if v_payment.method<>'cod' then raise exception 'cod_cancellation_beta_only'; end if;
  if v_payment.status<>'pending' then raise exception 'pending_cod_payment_required'; end if;

  select * into v_existing
  from private.order_cancellation_requests cr
  where cr.order_id=v_order.id and cr.status='requested'
  order by cr.submitted_at desc
  limit 1;
  if found then
    return jsonb_build_object(
      'requestId',v_existing.id,
      'requestStatus',v_existing.status,
      'orderStatus',v_order.status,
      'requiresAdminReview',true,
      'changed',false
    );
  end if;

  if v_order.status in ('received','confirmed') then
    v_requires_review:=false;
  elsif v_order.status in ('preparing','ready_for_courier_pickup') then
    v_requires_review:=true;
  else
    raise exception 'cancellation_state_not_allowed';
  end if;

  insert into private.order_cancellation_requests(
    order_id,customer_user_id,requester_kind,reason_text,requires_admin_review,status,
    resolved_at,resolved_by_user_id
  ) values (
    v_order.id,p_customer_user_id,p_requester_kind,trim(p_reason),v_requires_review,
    case when v_requires_review then 'requested' else 'approved' end,
    case when v_requires_review then null else v_now end,
    null
  ) returning * into v_request;

  insert into private.order_cancellation_events(
    cancellation_request_id,order_id,event_type,event_source,actor_user_id,metadata
  ) values (
    v_request.id,v_order.id,
    case when v_requires_review then 'cancellation_requested' else 'cancellation_auto_approved' end,
    'customer',p_customer_user_id,
    jsonb_build_object('requester_kind',p_requester_kind,'order_status_at_request',v_order.status)
  );

  if not v_requires_review then
    select * into v_cancel from private.cancel_pending_cod_order(
      v_order.id,v_request.id,p_customer_user_id,'customer_cancellation_before_preparing'
    );
    insert into private.order_cancellation_events(
      cancellation_request_id,order_id,event_type,event_source,actor_user_id,metadata
    ) values (
      v_request.id,v_order.id,'order_cancelled','system',p_customer_user_id,
      jsonb_build_object('restored_quantity',v_cancel.restored_quantity)
    );
  end if;

  return jsonb_build_object(
    'requestId',v_request.id,
    'requestStatus',v_request.status,
    'orderStatus',case when v_requires_review then v_order.status else 'cancelled' end,
    'requiresAdminReview',v_requires_review,
    'changed',true
  );
end;
$function$;

create or replace function public.create_customer_order_cancellation_request(
  p_order_id uuid,
  p_customer_user_id uuid,
  p_reason text
)
returns jsonb
language sql
security definer
set search_path to ''
as $function$
  select private.create_order_cancellation_request_common(
    p_order_id,'authenticated_customer',p_customer_user_id,null,p_reason
  );
$function$;

create or replace function public.create_guest_order_cancellation_request(
  p_order_id uuid,
  p_guest_access_token_hash text,
  p_reason text
)
returns jsonb
language sql
security definer
set search_path to ''
as $function$
  select private.create_order_cancellation_request_common(
    p_order_id,'guest_customer',null,p_guest_access_token_hash,p_reason
  );
$function$;

create or replace function public.get_order_cancellation_context(
  p_order_id uuid,
  p_customer_user_id uuid,
  p_guest_access_token_hash text
)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $function$
declare
  v_order public.orders%rowtype;
  v_request private.order_cancellation_requests%rowtype;
  v_mode text;
begin
  select * into v_order from public.orders where id=p_order_id;
  if not found then return null; end if;

  if p_customer_user_id is not null then
    if v_order.customer_user_id is distinct from p_customer_user_id then return null; end if;
  else
    if v_order.customer_user_id is not null
       or p_guest_access_token_hash is null
       or v_order.guest_access_token_hash is distinct from p_guest_access_token_hash then return null; end if;
  end if;

  select * into v_request
  from private.order_cancellation_requests cr
  where cr.order_id=v_order.id
  order by cr.submitted_at desc
  limit 1;

  if v_order.status='cancelled' then v_mode:='cancelled';
  elsif v_request.id is not null and v_request.status='requested' then v_mode:='pending_review';
  elsif v_order.status in ('received','confirmed') then v_mode:='direct';
  elsif v_order.status in ('preparing','ready_for_courier_pickup') then v_mode:='review';
  else v_mode:='unavailable';
  end if;

  return jsonb_build_object(
    'orderId',v_order.id,
    'orderNumber',v_order.order_number,
    'orderStatus',v_order.status,
    'mode',v_mode,
    'latestRequest',case when v_request.id is null then null else jsonb_build_object(
      'id',v_request.id,
      'status',v_request.status,
      'requiresAdminReview',v_request.requires_admin_review,
      'reason',v_request.reason_text,
      'submittedAt',v_request.submitted_at,
      'resolvedAt',v_request.resolved_at,
      'resolutionNote',v_request.resolution_note
    ) end
  );
end;
$function$;

create or replace function public.get_admin_order_cancellation_requests()
returns table(
  request_id uuid,
  order_id uuid,
  order_number text,
  requester_kind text,
  reason_text text,
  submitted_at timestamptz,
  order_status text,
  payment_status text,
  currency_code text,
  final_total text
)
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if (select auth.uid()) is null or not (select private.is_super_admin()) then
    raise exception 'admin_required' using errcode='42501';
  end if;
  return query
  select cr.id,o.id,o.order_number,cr.requester_kind,cr.reason_text,cr.submitted_at,
         o.status,o.payment_status,o.currency_code,o.final_total::text
  from private.order_cancellation_requests cr
  join public.orders o on o.id=cr.order_id
  where cr.status='requested'
  order by cr.submitted_at asc,cr.id;
end;
$function$;

create or replace function public.admin_review_order_cancellation_request(
  p_request_id uuid,
  p_decision text,
  p_note text default null
)
returns table(request_id uuid,request_status text,order_status text,changed boolean)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_user_id uuid:=(select auth.uid());
  v_request private.order_cancellation_requests%rowtype;
  v_cancel record;
  v_now timestamptz:=now();
begin
  if v_user_id is null or not (select private.is_super_admin()) then
    raise exception 'admin_required' using errcode='42501';
  end if;
  if p_decision not in ('approved','rejected') then raise exception 'invalid_cancellation_decision'; end if;

  select * into v_request
  from private.order_cancellation_requests cr
  where cr.id=p_request_id
  for update;
  if not found then raise exception 'cancellation_request_not_found'; end if;

  if v_request.status=p_decision then
    return query select v_request.id,v_request.status,
      (select o.status from public.orders o where o.id=v_request.order_id),false;
    return;
  end if;
  if v_request.status<>'requested' then raise exception 'invalid_cancellation_review_state'; end if;
  if not v_request.requires_admin_review then raise exception 'cancellation_review_not_required'; end if;

  if p_decision='approved' then
    select * into v_cancel from private.cancel_pending_cod_order(
      v_request.order_id,v_request.id,v_user_id,'admin_cancellation_approved'
    );
  end if;

  update private.order_cancellation_requests
  set status=p_decision,resolved_at=v_now,resolved_by_user_id=v_user_id,
      resolution_note=nullif(trim(p_note),''),updated_at=v_now
  where id=v_request.id;

  insert into private.order_cancellation_events(
    cancellation_request_id,order_id,event_type,event_source,actor_user_id,metadata
  ) values (
    v_request.id,v_request.order_id,'cancellation_'||p_decision,'admin',v_user_id,
    jsonb_build_object('note',nullif(trim(p_note),''))
  );

  if p_decision='approved' then
    insert into private.order_cancellation_events(
      cancellation_request_id,order_id,event_type,event_source,actor_user_id,metadata
    ) values (
      v_request.id,v_request.order_id,'order_cancelled','admin',v_user_id,
      jsonb_build_object('restored_quantity',v_cancel.restored_quantity)
    );
  end if;

  return query select v_request.id,p_decision,
    (select o.status from public.orders o where o.id=v_request.order_id),true;
end;
$function$;

revoke all on function public.create_customer_order_cancellation_request(uuid,uuid,text) from public,anon,authenticated;
revoke all on function public.create_guest_order_cancellation_request(uuid,text,text) from public,anon,authenticated;
revoke all on function public.get_order_cancellation_context(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.create_customer_order_cancellation_request(uuid,uuid,text) to service_role;
grant execute on function public.create_guest_order_cancellation_request(uuid,text,text) to service_role;
grant execute on function public.get_order_cancellation_context(uuid,uuid,text) to service_role;

revoke all on function public.get_admin_order_cancellation_requests() from public,anon;
revoke all on function public.admin_review_order_cancellation_request(uuid,text,text) from public,anon;
grant execute on function public.get_admin_order_cancellation_requests() to authenticated;
grant execute on function public.admin_review_order_cancellation_request(uuid,text,text) to authenticated;
