-- M6.1 — Payout Account + Verification Foundation
-- Approved: Bank Transfer is the first payout method.
-- Sensitive payout details are stored only as opaque encrypted payloads.
-- Any add/change stays Pending Verification until IRTH approval.

create or replace function private.is_super_admin_user(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = p_user_id
      and r.code = 'super_admin'
  );
$$;

revoke all on function private.is_super_admin_user(uuid)
from public, anon, authenticated, service_role;

create table private.artisan_payout_accounts (
  id uuid primary key default gen_random_uuid(),
  artisan_id uuid not null references public.artisan_profiles(id) on delete restrict,
  method text not null,
  status text not null default 'pending_verification',
  details_ciphertext text not null,
  details_fingerprint text not null,
  encryption_key_version integer not null,
  requested_by_user_id uuid not null references auth.users(id) on delete restrict,
  requested_at timestamptz not null default now(),
  reviewed_by_user_id uuid references auth.users(id) on delete restrict,
  reviewed_at timestamptz,
  review_note text,
  activated_at timestamptz,
  superseded_by_account_id uuid references private.artisan_payout_accounts(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint artisan_payout_accounts_method_values
    check (method in ('bank_transfer')),
  constraint artisan_payout_accounts_status_values
    check (status in ('pending_verification','active','rejected','superseded')),
  constraint artisan_payout_accounts_ciphertext_length
    check (length(details_ciphertext) between 24 and 20000),
  constraint artisan_payout_accounts_fingerprint_format
    check (details_fingerprint ~ '^[0-9a-f]{64}$'),
  constraint artisan_payout_accounts_key_version_positive
    check (encryption_key_version >= 1),
  constraint artisan_payout_accounts_review_note_length
    check (review_note is null or length(trim(review_note)) between 1 and 2000),
  constraint artisan_payout_accounts_state_consistency
    check (
      (status = 'pending_verification'
        and reviewed_by_user_id is null and reviewed_at is null
        and activated_at is null and superseded_by_account_id is null)
      or
      (status = 'active'
        and reviewed_by_user_id is not null and reviewed_at is not null
        and activated_at is not null and superseded_by_account_id is null)
      or
      (status = 'rejected'
        and reviewed_by_user_id is not null and reviewed_at is not null
        and activated_at is null and superseded_by_account_id is null)
      or
      (status = 'superseded'
        and reviewed_by_user_id is not null and reviewed_at is not null
        and activated_at is not null and superseded_by_account_id is not null)
    ),
  constraint artisan_payout_accounts_not_self_superseded
    check (superseded_by_account_id is null or superseded_by_account_id <> id)
);

create unique index artisan_payout_accounts_one_pending_per_method
  on private.artisan_payout_accounts(artisan_id, method)
  where status = 'pending_verification';

create unique index artisan_payout_accounts_one_active_per_method
  on private.artisan_payout_accounts(artisan_id, method)
  where status = 'active';

create index artisan_payout_accounts_artisan_status_idx
  on private.artisan_payout_accounts(artisan_id, status, created_at desc);

create table private.payout_account_events (
  id bigint generated by default as identity primary key,
  payout_account_id uuid not null references private.artisan_payout_accounts(id) on delete restrict,
  event_type text not null,
  event_source text not null,
  source_key text not null unique,
  actor_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint payout_account_events_type_nonblank check (length(trim(event_type)) >= 3),
  constraint payout_account_events_source_values check (event_source in ('artisan','admin','system')),
  constraint payout_account_events_source_key_nonblank check (length(trim(source_key)) >= 8),
  constraint payout_account_events_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create index payout_account_events_account_created_idx
  on private.payout_account_events(payout_account_id, created_at);

revoke all on private.artisan_payout_accounts from public, anon, authenticated, service_role;
revoke all on private.payout_account_events from public, anon, authenticated, service_role;
revoke all on sequence private.payout_account_events_id_seq from public, anon, authenticated, service_role;

create or replace function private.prevent_payout_account_sensitive_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.artisan_id is distinct from new.artisan_id
     or old.method is distinct from new.method
     or old.details_ciphertext is distinct from new.details_ciphertext
     or old.details_fingerprint is distinct from new.details_fingerprint
     or old.encryption_key_version is distinct from new.encryption_key_version
     or old.requested_by_user_id is distinct from new.requested_by_user_id
     or old.requested_at is distinct from new.requested_at
     or old.created_at is distinct from new.created_at then
    raise exception 'payout_account_sensitive_fields_are_immutable';
  end if;
  return new;
end;
$$;

revoke all on function private.prevent_payout_account_sensitive_mutation()
from public, anon, authenticated, service_role;

create trigger artisan_payout_accounts_sensitive_immutable
before update on private.artisan_payout_accounts
for each row execute function private.prevent_payout_account_sensitive_mutation();

create or replace function private.prevent_payout_account_event_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception 'payout_account_events_are_append_only';
end;
$$;

revoke all on function private.prevent_payout_account_event_mutation()
from public, anon, authenticated, service_role;

create trigger payout_account_events_append_only
before update or delete on private.payout_account_events
for each row execute function private.prevent_payout_account_event_mutation();

create or replace function private.require_artisan_payout_requester(
  p_artisan_id uuid,
  p_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_auth_user_id uuid;
  v_has_role boolean;
begin
  if p_artisan_id is null or p_user_id is null then
    raise exception 'artisan_and_requester_required' using errcode='42501';
  end if;

  select ap.auth_user_id into v_auth_user_id
  from public.artisan_profiles ap
  where ap.id = p_artisan_id
  for update;

  if not found or v_auth_user_id is distinct from p_user_id then
    raise exception 'artisan_payout_account_access_denied' using errcode='42501';
  end if;

  select exists (
    select 1
    from public.user_roles ur
    join public.roles r on r.id = ur.role_id
    where ur.user_id = p_user_id and r.code = 'artisan'
  ) into v_has_role;

  if not v_has_role then
    raise exception 'artisan_role_required' using errcode='42501';
  end if;
end;
$$;

revoke all on function private.require_artisan_payout_requester(uuid,uuid)
from public, anon, authenticated, service_role;

create or replace function private.submit_bank_transfer_payout_account_request(
  p_artisan_id uuid,
  p_requested_by_user_id uuid,
  p_details_ciphertext text,
  p_details_fingerprint text,
  p_encryption_key_version integer
)
returns table(payout_account_id uuid, status text, changed boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_pending_id uuid;
  v_pending_fingerprint text;
  v_active_id uuid;
  v_active_fingerprint text;
  v_account_id uuid;
begin
  perform private.require_artisan_payout_requester(p_artisan_id, p_requested_by_user_id);

  if p_details_ciphertext is null or length(p_details_ciphertext) not between 24 and 20000 then
    raise exception 'invalid_payout_account_ciphertext';
  end if;
  if p_details_fingerprint is null or p_details_fingerprint !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid_payout_account_fingerprint';
  end if;
  if p_encryption_key_version is null or p_encryption_key_version < 1 then
    raise exception 'invalid_payout_account_key_version';
  end if;

  select a.id, a.details_fingerprint
  into v_pending_id, v_pending_fingerprint
  from private.artisan_payout_accounts a
  where a.artisan_id = p_artisan_id
    and a.method = 'bank_transfer'
    and a.status = 'pending_verification'
  for update;

  if found then
    if v_pending_fingerprint = p_details_fingerprint then
      return query select v_pending_id, 'pending_verification'::text, false;
      return;
    end if;
    raise exception 'payout_account_verification_already_pending';
  end if;

  select a.id, a.details_fingerprint
  into v_active_id, v_active_fingerprint
  from private.artisan_payout_accounts a
  where a.artisan_id = p_artisan_id
    and a.method = 'bank_transfer'
    and a.status = 'active'
  for share;

  if found and v_active_fingerprint = p_details_fingerprint then
    return query select v_active_id, 'active'::text, false;
    return;
  end if;

  insert into private.artisan_payout_accounts(
    artisan_id, method, status, details_ciphertext, details_fingerprint,
    encryption_key_version, requested_by_user_id
  ) values (
    p_artisan_id, 'bank_transfer', 'pending_verification', p_details_ciphertext,
    p_details_fingerprint, p_encryption_key_version, p_requested_by_user_id
  ) returning id into v_account_id;

  insert into private.payout_account_events(
    payout_account_id,event_type,event_source,source_key,actor_user_id,metadata
  ) values (
    v_account_id,'payout_account_submitted','artisan',
    'payout-account-submitted:'||v_account_id::text,
    p_requested_by_user_id,
    jsonb_build_object('method','bank_transfer','is_change_request',v_active_id is not null)
  );

  return query select v_account_id, 'pending_verification'::text, true;
end;
$$;

revoke all on function private.submit_bank_transfer_payout_account_request(uuid,uuid,text,text,integer)
from public, anon, authenticated, service_role;

create or replace function public.submit_bank_transfer_payout_account_request(
  p_artisan_id uuid,
  p_requested_by_user_id uuid,
  p_details_ciphertext text,
  p_details_fingerprint text,
  p_encryption_key_version integer
)
returns table(payout_account_id uuid, status text, changed boolean)
language sql
security definer
set search_path = ''
as $$
  select * from private.submit_bank_transfer_payout_account_request(
    p_artisan_id,p_requested_by_user_id,p_details_ciphertext,p_details_fingerprint,p_encryption_key_version
  );
$$;

revoke all on function public.submit_bank_transfer_payout_account_request(uuid,uuid,text,text,integer)
from public, anon, authenticated, service_role;
grant execute on function public.submit_bank_transfer_payout_account_request(uuid,uuid,text,text,integer)
to service_role;

create or replace function private.review_payout_account_request(
  p_payout_account_id uuid,
  p_decision text,
  p_admin_user_id uuid,
  p_review_note text default null
)
returns table(payout_account_id uuid, status text, changed boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_account private.artisan_payout_accounts%rowtype;
  v_old_active_id uuid;
  v_now timestamptz := now();
  v_target_status text;
begin
  if p_admin_user_id is null or not private.is_super_admin_user(p_admin_user_id) then
    raise exception 'admin_required' using errcode='42501';
  end if;
  if p_decision not in ('approved','rejected') then
    raise exception 'invalid_payout_account_decision';
  end if;
  if p_review_note is not null and length(trim(p_review_note)) not between 1 and 2000 then
    raise exception 'invalid_payout_account_review_note';
  end if;

  select a.* into v_account
  from private.artisan_payout_accounts a
  where a.id = p_payout_account_id
  for update;
  if not found then raise exception 'payout_account_not_found'; end if;

  v_target_status := case when p_decision='approved' then 'active' else 'rejected' end;

  if v_account.status = v_target_status then
    return query select v_account.id, v_account.status, false;
    return;
  end if;
  if v_account.status <> 'pending_verification' then
    raise exception 'invalid_payout_account_review_state';
  end if;

  if p_decision = 'approved' then
    select a.id into v_old_active_id
    from private.artisan_payout_accounts a
    where a.artisan_id = v_account.artisan_id
      and a.method = v_account.method
      and a.status = 'active'
      and a.id <> v_account.id
    for update;

    if found then
      update private.artisan_payout_accounts a
      set status='superseded', superseded_by_account_id=v_account.id, updated_at=v_now
      where a.id=v_old_active_id;

      insert into private.payout_account_events(
        payout_account_id,event_type,event_source,source_key,actor_user_id,metadata
      ) values (
        v_old_active_id,'payout_account_superseded','admin',
        'payout-account-superseded:'||v_old_active_id::text||':'||v_account.id::text,
        p_admin_user_id,jsonb_build_object('replacement_account_id',v_account.id)
      );
    end if;

    update private.artisan_payout_accounts a
    set status='active', reviewed_by_user_id=p_admin_user_id, reviewed_at=v_now,
        review_note=nullif(trim(p_review_note),''), activated_at=v_now, updated_at=v_now
    where a.id=v_account.id;

    insert into private.payout_account_events(
      payout_account_id,event_type,event_source,source_key,actor_user_id,metadata
    ) values (
      v_account.id,'payout_account_approved','admin',
      'payout-account-approved:'||v_account.id::text,
      p_admin_user_id,'{}'::jsonb
    );
  else
    update private.artisan_payout_accounts a
    set status='rejected', reviewed_by_user_id=p_admin_user_id, reviewed_at=v_now,
        review_note=nullif(trim(p_review_note),''), updated_at=v_now
    where a.id=v_account.id;

    insert into private.payout_account_events(
      payout_account_id,event_type,event_source,source_key,actor_user_id,metadata
    ) values (
      v_account.id,'payout_account_rejected','admin',
      'payout-account-rejected:'||v_account.id::text,
      p_admin_user_id,'{}'::jsonb
    );
  end if;

  return query select v_account.id, v_target_status, true;
end;
$$;

revoke all on function private.review_payout_account_request(uuid,text,uuid,text)
from public, anon, authenticated, service_role;

create or replace function public.review_payout_account_request(
  p_payout_account_id uuid,
  p_decision text,
  p_admin_user_id uuid,
  p_review_note text default null
)
returns table(payout_account_id uuid, status text, changed boolean)
language sql
security definer
set search_path = ''
as $$
  select * from private.review_payout_account_request(
    p_payout_account_id,p_decision,p_admin_user_id,p_review_note
  );
$$;

revoke all on function public.review_payout_account_request(uuid,text,uuid,text)
from public, anon, authenticated, service_role;
grant execute on function public.review_payout_account_request(uuid,text,uuid,text)
to service_role;

create or replace function public.get_artisan_payout_account_status(
  p_artisan_id uuid,
  p_requester_user_id uuid
)
returns table(
  payout_account_id uuid,
  method text,
  status text,
  requested_at timestamptz,
  reviewed_at timestamptz,
  activated_at timestamptz,
  review_note text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.require_artisan_payout_requester(p_artisan_id,p_requester_user_id);
  return query
  select a.id,a.method,a.status,a.requested_at,a.reviewed_at,a.activated_at,a.review_note
  from private.artisan_payout_accounts a
  where a.artisan_id=p_artisan_id
    and a.status in ('pending_verification','active','rejected')
  order by case a.status when 'pending_verification' then 1 when 'active' then 2 else 3 end,
           a.created_at desc;
end;
$$;

revoke all on function public.get_artisan_payout_account_status(uuid,uuid)
from public, anon, authenticated, service_role;
grant execute on function public.get_artisan_payout_account_status(uuid,uuid)
to service_role;

create or replace function public.get_payout_accounts_for_admin(
  p_admin_user_id uuid,
  p_artisan_id uuid default null
)
returns table(
  payout_account_id uuid,
  artisan_id uuid,
  method text,
  status text,
  details_ciphertext text,
  details_fingerprint text,
  encryption_key_version integer,
  requested_by_user_id uuid,
  requested_at timestamptz,
  reviewed_by_user_id uuid,
  reviewed_at timestamptz,
  review_note text,
  activated_at timestamptz,
  superseded_by_account_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_admin_user_id is null or not private.is_super_admin_user(p_admin_user_id) then
    raise exception 'admin_required' using errcode='42501';
  end if;
  return query
  select a.id,a.artisan_id,a.method,a.status,a.details_ciphertext,a.details_fingerprint,
         a.encryption_key_version,a.requested_by_user_id,a.requested_at,
         a.reviewed_by_user_id,a.reviewed_at,a.review_note,a.activated_at,
         a.superseded_by_account_id
  from private.artisan_payout_accounts a
  where p_artisan_id is null or a.artisan_id=p_artisan_id
  order by a.created_at desc;
end;
$$;

revoke all on function public.get_payout_accounts_for_admin(uuid,uuid)
from public, anon, authenticated, service_role;
grant execute on function public.get_payout_accounts_for_admin(uuid,uuid)
to service_role;
