create table private.return_requests (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete restrict,
  customer_user_id uuid references auth.users(id) on delete set null,
  requester_kind text not null,
  status text not null default 'requested',
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by_user_id uuid references auth.users(id) on delete set null,
  review_note text,
  received_at timestamptz,
  inspected_at timestamptz,
  inspection_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint return_requests_requester_kind_values check (requester_kind in ('authenticated_customer','guest_customer')),
  constraint return_requests_status_values check (status in ('requested','approved','rejected','received','inspected','refund_pending','partially_refunded','refunded')),
  constraint return_requests_review_consistency check (
    (status = 'requested' and reviewed_at is null and reviewed_by_user_id is null)
    or (status <> 'requested' and reviewed_at is not null and reviewed_by_user_id is not null)
  ),
  constraint return_requests_received_consistency check (
    (status in ('received','inspected','refund_pending','partially_refunded','refunded')) = (received_at is not null)
  ),
  constraint return_requests_inspected_consistency check (
    (status in ('inspected','refund_pending','partially_refunded','refunded')) = (inspected_at is not null)
  )
);

create table private.return_request_items (
  id uuid primary key default gen_random_uuid(),
  return_request_id uuid not null references private.return_requests(id) on delete restrict,
  order_item_id uuid not null references public.order_items(id) on delete restrict,
  quantity integer not null,
  reason_text text not null,
  restockable_quantity integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint return_request_items_quantity_positive check (quantity > 0),
  constraint return_request_items_reason_length check (length(trim(reason_text)) between 3 and 1000),
  constraint return_request_items_restockable_range check (
    restockable_quantity is null or (restockable_quantity >= 0 and restockable_quantity <= quantity)
  ),
  constraint return_request_items_request_order_item_unique unique (return_request_id, order_item_id)
);

create table private.return_request_events (
  id bigint generated by default as identity primary key,
  return_request_id uuid not null references private.return_requests(id) on delete restrict,
  event_type text not null,
  event_source text not null,
  source_key text not null unique,
  actor_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint return_request_events_type_nonblank check (length(trim(event_type)) >= 3),
  constraint return_request_events_source_values check (event_source in ('customer','admin','system')),
  constraint return_request_events_source_key_nonblank check (length(trim(source_key)) >= 8),
  constraint return_request_events_metadata_object check (jsonb_typeof(metadata) = 'object')
);

create index return_requests_order_status_idx on private.return_requests(order_id, status);
create index return_request_items_order_item_idx on private.return_request_items(order_item_id);
create index return_request_events_request_created_idx on private.return_request_events(return_request_id, created_at);

revoke all on private.return_requests from public, anon, authenticated, service_role;
revoke all on private.return_request_items from public, anon, authenticated, service_role;
revoke all on private.return_request_events from public, anon, authenticated, service_role;
grant select on private.return_requests to service_role;
grant select on private.return_request_items to service_role;
grant select on private.return_request_events to service_role;

create or replace function private.prevent_return_event_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'return_events_are_append_only';
end;
$$;

revoke all on function private.prevent_return_event_mutation() from public, anon, authenticated, service_role;

create trigger return_request_events_prevent_update_delete
before update or delete on private.return_request_events
for each row execute function private.prevent_return_event_mutation();

create or replace function private.create_return_request_common(
  p_order_id uuid,
  p_requester_kind text,
  p_requester_user_id uuid,
  p_guest_access_token_hash text,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order public.orders%rowtype;
  v_request_id uuid;
  v_item jsonb;
  v_order_item_id uuid;
  v_quantity integer;
  v_reason text;
  v_order_quantity integer;
  v_reserved_quantity integer;
begin
  if p_order_id is null then raise exception 'order_required'; end if;
  if p_requester_kind not in ('authenticated_customer','guest_customer') then raise exception 'invalid_requester_kind'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 50 then
    raise exception 'invalid_return_items';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;
  if v_order.status = 'cancelled' then raise exception 'cancelled_order_not_returnable'; end if;

  if p_requester_kind = 'authenticated_customer' then
    if p_requester_user_id is null or v_order.customer_user_id is distinct from p_requester_user_id then
      raise exception 'return_order_access_denied' using errcode = '42501';
    end if;
  else
    if v_order.customer_user_id is not null
       or p_guest_access_token_hash is null
       or length(trim(p_guest_access_token_hash)) < 32
       or v_order.guest_access_token_hash is distinct from p_guest_access_token_hash then
      raise exception 'return_order_access_denied' using errcode = '42501';
    end if;
  end if;

  insert into private.return_requests(order_id, customer_user_id, requester_kind)
  values (p_order_id, v_order.customer_user_id, p_requester_kind)
  returning id into v_request_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    begin
      v_order_item_id := nullif(trim(v_item->>'orderItemId'),'')::uuid;
      v_quantity := (v_item->>'quantity')::integer;
      v_reason := trim(coalesce(v_item->>'reason',''));
    exception when others then
      raise exception 'invalid_return_item';
    end;

    if v_order_item_id is null or v_quantity is null or v_quantity <= 0 or length(v_reason) not between 3 and 1000 then
      raise exception 'invalid_return_item';
    end if;

    select oi.quantity into v_order_quantity
    from public.order_items oi
    where oi.id = v_order_item_id and oi.order_id = p_order_id;
    if not found then raise exception 'return_item_not_in_order'; end if;

    select coalesce(sum(ri.quantity),0)::integer into v_reserved_quantity
    from private.return_request_items ri
    join private.return_requests rr on rr.id = ri.return_request_id
    where ri.order_item_id = v_order_item_id
      and rr.status <> 'rejected';

    if v_quantity > (v_order_quantity - v_reserved_quantity) then
      raise exception 'return_quantity_exceeds_available';
    end if;

    begin
      insert into private.return_request_items(return_request_id, order_item_id, quantity, reason_text)
      values (v_request_id, v_order_item_id, v_quantity, v_reason);
    exception when unique_violation then
      raise exception 'duplicate_return_order_item';
    end;
  end loop;

  insert into private.return_request_events(return_request_id,event_type,event_source,source_key,actor_user_id,metadata)
  values (
    v_request_id,
    'return_requested',
    'customer',
    'return-requested:' || v_request_id::text,
    p_requester_user_id,
    jsonb_build_object('requester_kind', p_requester_kind)
  );

  return v_request_id;
end;
$$;

revoke all on function private.create_return_request_common(uuid,text,uuid,text,jsonb) from public, anon, authenticated, service_role;

create or replace function public.create_my_return_request(p_order_id uuid, p_items jsonb)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
begin
  if v_user_id is null then raise exception 'authentication_required' using errcode='42501'; end if;
  return private.create_return_request_common(p_order_id,'authenticated_customer',v_user_id,null,p_items);
end;
$$;
revoke all on function public.create_my_return_request(uuid,jsonb) from public, anon, authenticated, service_role;
grant execute on function public.create_my_return_request(uuid,jsonb) to authenticated;

create or replace function public.create_guest_return_request(p_order_id uuid, p_guest_access_token_hash text, p_items jsonb)
returns uuid
language sql
security definer
set search_path = ''
as $$
  select private.create_return_request_common(p_order_id,'guest_customer',null,p_guest_access_token_hash,p_items);
$$;
revoke all on function public.create_guest_return_request(uuid,text,jsonb) from public, anon, authenticated, service_role;
grant execute on function public.create_guest_return_request(uuid,text,jsonb) to service_role;

create or replace function private.review_return_request(p_return_request_id uuid, p_decision text, p_note text default null)
returns table(return_request_id uuid, status text, changed boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_status text;
  v_now timestamptz := now();
begin
  if v_user_id is null or not (select private.is_super_admin()) then raise exception 'admin_required' using errcode='42501'; end if;
  if p_decision not in ('approved','rejected') then raise exception 'invalid_return_decision'; end if;

  select rr.status into v_status from private.return_requests rr where rr.id=p_return_request_id for update;
  if not found then raise exception 'return_request_not_found'; end if;
  if v_status = p_decision then return query select p_return_request_id,v_status,false; return; end if;
  if v_status <> 'requested' then raise exception 'invalid_return_review_state'; end if;

  update private.return_requests
  set status=p_decision, reviewed_at=v_now, reviewed_by_user_id=v_user_id,
      review_note=nullif(trim(p_note),''), updated_at=v_now
  where id=p_return_request_id;

  insert into private.return_request_events(return_request_id,event_type,event_source,source_key,actor_user_id,metadata)
  values(p_return_request_id,'return_'||p_decision,'admin','return-'||p_decision||':'||p_return_request_id::text,v_user_id,'{}'::jsonb);

  return query select p_return_request_id,p_decision,true;
end;
$$;
revoke all on function private.review_return_request(uuid,text,text) from public, anon, authenticated, service_role;

create or replace function public.review_return_request(p_return_request_id uuid, p_decision text, p_note text default null)
returns table(return_request_id uuid, status text, changed boolean)
language sql
security definer
set search_path = ''
as $$ select * from private.review_return_request(p_return_request_id,p_decision,p_note); $$;
revoke all on function public.review_return_request(uuid,text,text) from public, anon, authenticated, service_role;
grant execute on function public.review_return_request(uuid,text,text) to authenticated;

create or replace function private.mark_return_received(p_return_request_id uuid)
returns table(return_request_id uuid, status text, changed boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_status text;
  v_now timestamptz := now();
begin
  if v_user_id is null or not (select private.is_super_admin()) then raise exception 'admin_required' using errcode='42501'; end if;
  select rr.status into v_status from private.return_requests rr where rr.id=p_return_request_id for update;
  if not found then raise exception 'return_request_not_found'; end if;
  if v_status in ('received','inspected','refund_pending','partially_refunded','refunded') then
    return query select p_return_request_id,v_status,false; return;
  end if;
  if v_status <> 'approved' then raise exception 'invalid_return_receive_state'; end if;

  update private.return_requests set status='received',received_at=v_now,updated_at=v_now where id=p_return_request_id;
  insert into private.return_request_events(return_request_id,event_type,event_source,source_key,actor_user_id,metadata)
  values(p_return_request_id,'return_received','admin','return-received:'||p_return_request_id::text,v_user_id,'{}'::jsonb);
  return query select p_return_request_id,'received',true;
end;
$$;
revoke all on function private.mark_return_received(uuid) from public, anon, authenticated, service_role;

create or replace function public.mark_return_received(p_return_request_id uuid)
returns table(return_request_id uuid, status text, changed boolean)
language sql
security definer
set search_path = ''
as $$ select * from private.mark_return_received(p_return_request_id); $$;
revoke all on function public.mark_return_received(uuid) from public, anon, authenticated, service_role;
grant execute on function public.mark_return_received(uuid) to authenticated;

create or replace function private.inspect_return_request(p_return_request_id uuid, p_items jsonb, p_note text default null)
returns table(return_request_id uuid, status text, changed boolean)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_status text;
  v_item jsonb;
  v_return_item_id uuid;
  v_restockable integer;
  v_qty integer;
  v_expected integer;
  v_seen integer := 0;
  v_now timestamptz := now();
begin
  if v_user_id is null or not (select private.is_super_admin()) then raise exception 'admin_required' using errcode='42501'; end if;
  select rr.status into v_status from private.return_requests rr where rr.id=p_return_request_id for update;
  if not found then raise exception 'return_request_not_found'; end if;
  if v_status = 'inspected' then return query select p_return_request_id,v_status,false; return; end if;
  if v_status <> 'received' then raise exception 'invalid_return_inspection_state'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then raise exception 'invalid_inspection_items'; end if;

  select count(*) into v_expected from private.return_request_items where return_request_id=p_return_request_id;
  if jsonb_array_length(p_items) <> v_expected then raise exception 'inspection_must_cover_all_return_items'; end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    begin
      v_return_item_id := nullif(trim(v_item->>'returnItemId'),'')::uuid;
      v_restockable := (v_item->>'restockableQuantity')::integer;
    exception when others then raise exception 'invalid_inspection_item'; end;

    select ri.quantity into v_qty from private.return_request_items ri
    where ri.id=v_return_item_id and ri.return_request_id=p_return_request_id for update;
    if not found or v_restockable is null or v_restockable < 0 or v_restockable > v_qty then
      raise exception 'invalid_inspection_item';
    end if;
    if (select restockable_quantity from private.return_request_items where id=v_return_item_id) is not null then
      raise exception 'duplicate_inspection_item';
    end if;
    update private.return_request_items set restockable_quantity=v_restockable,updated_at=v_now where id=v_return_item_id;
    v_seen := v_seen + 1;
  end loop;

  if v_seen <> v_expected then raise exception 'inspection_must_cover_all_return_items'; end if;
  update private.return_requests set status='inspected',inspected_at=v_now,inspection_note=nullif(trim(p_note),''),updated_at=v_now where id=p_return_request_id;
  insert into private.return_request_events(return_request_id,event_type,event_source,source_key,actor_user_id,metadata)
  values(p_return_request_id,'return_inspected','admin','return-inspected:'||p_return_request_id::text,v_user_id,jsonb_build_object('item_count',v_seen));
  return query select p_return_request_id,'inspected',true;
end;
$$;
revoke all on function private.inspect_return_request(uuid,jsonb,text) from public, anon, authenticated, service_role;

create or replace function public.inspect_return_request(p_return_request_id uuid, p_items jsonb, p_note text default null)
returns table(return_request_id uuid, status text, changed boolean)
language sql
security definer
set search_path = ''
as $$ select * from private.inspect_return_request(p_return_request_id,p_items,p_note); $$;
revoke all on function public.inspect_return_request(uuid,jsonb,text) from public, anon, authenticated, service_role;
grant execute on function public.inspect_return_request(uuid,jsonb,text) to authenticated;